// English source keys keep persisted data language-neutral.
const catalog = {
  "si": {
    "Text size": "පෙළ ප්‍රමාණය",
    "Font size": "අකුරු ප්‍රමාණය",
    "Adjust text across the app. Your device accessibility setting is also respected.":
        "යෙදුම පුරා පෙළ ප්‍රමාණය සකසන්න. උපාංගයේ ප්‍රවේශතා සැකසුමද භාවිත වේ.",
    "Reset text size": "පෙළ ප්‍රමාණය යළි සකසන්න",

    "Home": "මුල් පිටුව",
    "Calendar": "දින දර්ශනය",
    "Insights": "අවබෝධය",
    "More": "තවත්",
    "Chat": "කතාබහ",
    "Get Started": "ආරම්භ කරන්න",
    "Welcome to": "සාදරයෙන් පිළිගනිමු",
    "Your personal companion for every stage of your journey.":
        "ඔබේ ගමනේ සෑම පියවරකටම ඔබේ සහකාරිය.",
    "I already have an account": "මට දැනටමත් ගිණුමක් ඇත",
    "Continue": "ඉදිරියට",
    "Save": "සුරකින්න",
    "Language": "භාෂාව",
    "Appearance": "පෙනුම",
    "Good morning": "සුබ උදෑසනක්",
    "How are you feeling?": "ඔබට කොහොමද?",
    "Log Period": "ඔසප් වීම සටහන් කරන්න",
    "Today": "අද",
    "Settings": "සැකසුම්",
    "Your privacy is our priority": "ඔබේ පෞද්ගලිකත්වය අපගේ ප්‍රමුඛතාවයි",
    "Period": "ඔසප් වීම",
    "Symptoms": "ලක්ෂණ",
    "Mood": "මනෝභාවය",
    "Sleep": "නින්ද",
    "Water": "ජලය",
    "Exercise": "ව්‍යායාම",
    "Nutrition": "පෝෂණය",
    "Weight": "බර",
    "Self-Care": "ස්වයං රැකවරණය",
    "Energy": "ශක්තිය",
    "Steps": "පියවර",
    "Medication": "ඖෂධ",
    "Skin": "සම",
    "Journal": "දිනපොත",
    "Cramps": "කැක්කුම",
    "Headache": "හිසරදය",
    "Bloating": "බඩ පිපීම",
    "Mood changes": "මනෝභාව වෙනස්කම්",
    "Acne": "කුරුලෑ",
    "Fatigue": "විඩාව",
    "Breast tenderness": "පියයුරු සංවේදීතාව",
    "Cravings": "ආහාර ආශාවන්",
    "Back pain": "කොන්දේ වේදනාව",
    "Light": "සැහැල්ලු",
    "Medium": "මධ්‍යම",
    "Heavy": "අධික",
    "Spotting": "සුළු රුධිර පැල්ලම්",
    "Great": "ඉතා හොඳයි",
    "Good": "හොඳයි",
    "Okay": "සාමාන්‍යයි",
    "Low": "අඩුයි",
    "Anxious": "කනස්සල්ලෙන්",
    "High": "ඉහළයි",
    "Steady": "ස්ථාවරයි",
    "Clear": "පැහැදිලි",
    "Dry": "වියළි",
    "Oily": "තෙල් සහිත",
    "Sensitive": "සංවේදී",
    "Entry": "සටහන",
    "Your entry": "ඔබේ සටහන",
    "Notes (optional)": "සටහන් (අවශ්‍ය නම්)",
    "A little space for how you feel…": "ඔබේ හැඟීම් සඳහා ඉඩක්…",
    "Add an entry before saving.": "සුරැකීමට පෙර සටහනක් එක් කරන්න.",
    "Could not save. Please try again.":
        "සුරැකිය නොහැකි විය. නැවත උත්සාහ කරන්න.",
    "Close tracker": "සටහන් පුවරුව වසන්න",
    "See All": "සියල්ල බලන්න",
    "Your private wellbeing companion": "ඔබේ පෞද්ගලික සුවතා සහකාරිය",
    "Hi": "ආයුබෝවන්",
    "I’m Herly AI, here to listen, answer your questions and support you on your journey.": "මම Herly AI. ඔබට සවන් දීමටත්, ප්‍රශ්නවලට පිළිතුරු දීමටත්, ඔබේ ගමනට සහාය වීමටත් මෙහි සිටිමි.",
    "Ask anything": "ඕනෑම දෙයක් අසන්න",
    "Get personalized insights": "පුද්ගලික අවබෝධ ලබාගන්න",
    "Practical tips & guidance": "ප්‍රායෝගික උපදෙස් හා මඟපෙන්වීම",
    "Safe & private space": "ආරක්ෂිත පුද්ගලික ඉඩක්",
    "Your conversations stay on this device. Demo replies.":
        "ඔබේ කතාබහ මෙම උපාංගයේ පවතී. ආදර්ශ පිළිතුරු.",
    "I’ve been feeling more tired than usual this week. Any ideas why?":
        "මේ සතියේ මට වෙනදාට වඩා විඩාවක් දැනෙනවා. ඒ ඇයි කියා අදහසක් තිබෙනවාද?",
    "Herly is typing…": "Herly ලියමින් සිටී…",
    "You might also like to ask:": "ඔබට මේවාත් ඇසිය හැකිය:",
    "How can I improve my sleep?": "මගේ නින්ද දියුණු කරගන්නේ කෙසේද?",
    "What foods boost my energy?": "මගේ ශක්තිය වැඩි කරන ආහාර මොනවාද?",
    "Is my period coming soon?": "මගේ ඔසප් වීම ළඟද?",
    "Ask Herly anything…": "Herly වෙතින් ඕනෑම දෙයක් අසන්න…",
    "Sample conversation": "ආදර්ශ කතාබහ",
    "Sent": "යැවුවා",
    "Demo response": "ආදර්ශ පිළිතුර",
    "Helpful": "ප්‍රයෝජනවත්",
    "Not helpful": "ප්‍රයෝජනවත් නැත",
    "Copy response": "පිළිතුර පිටපත් කරන්න",
    "Response copied.": "පිළිතුර පිටපත් කළා.",
    "Open support resources": "සහාය තොරතුරු විවෘත කරන්න",
    "Back to Home": "මුල් පිටුවට",
    "Conversation history": "කතාබහ ඉතිහාසය",
    "Your conversations will appear here.": "ඔබේ කතාබහ මෙහි දිස්වනු ඇත.",
    "Chat settings": "කතාබහ සැකසුම්",
    "More suggestions": "තවත් යෝජනා",
    "Attachments (demo)": "ඇමුණුම් (ආදර්ශ)",
    "Attachments are a demo placeholder.": "ඇමුණුම් ආදර්ශ පහසුකමකි.",
    "Voice (demo)": "හඬ (ආදර්ශ)",
    "Voice input is a demo placeholder.": "හඬ ඇතුළත් කිරීම ආදර්ශ පහසුකමකි.",
    "Send message": "පණිවිඩය යවන්න",
    "Choose date": "දිනය තෝරන්න",
    "Calendar settings": "දින දර්ශන සැකසුම්",
    "Previous month": "පෙර මාසය",
    "Next month": "ඊළඟ මාසය",
    "Fertile Window": "සරු කාලය",
    "Fertile window": "සරු කාලය",
    "Ovulation": "ඩිම්බ මෝචනය",
    "Special Day": "විශේෂ දිනය",
    "Notes": "සටහන්",
    "Demo": "ආදර්ශය",
    "Selected day": "තෝරාගත් දිනය",
    "Next day": "ඊළඟ දිනය",
    "Your daily wellbeing": "ඔබේ දෛනික සුවතාව",
    "Take it easy and be kind to yourself.":
        "සැහැල්ලුවෙන් සිටින්න. ඔබට කාරුණික වන්න.",
    "Flow": "රුධිර ප්‍රවාහය",
    "Mild": "සුළු",
    "Calm": "සන්සුන්",
    "Not logged": "සටහන් කර නැත",
    "Log Today": "අද සටහන් කරන්න",
    "Today’s Insights": "අද අවබෝධය",
    "Your energy may be lower today. Try gentle movement, stay hydrated and consider iron-rich foods.": "අද ශක්තිය අඩු විය හැකිය. සැහැල්ලු චලනය, ප්‍රමාණවත් ජලය සහ යකඩ සහිත ආහාර සලකා බලන්න.",
    "Cycle Phase": "චක්‍ර අවධිය",
    "Menstrual Phase": "ඔසප් අවධිය",
    "Your cycle": "ඔබේ චක්‍රය",
    "Your period has started. This phase usually lasts 3–7 days.":
        "ඔබේ ඔසප් වීම ඇරඹී ඇත. මෙම අවධිය සාමාන්‍යයෙන් දින 3–7 ක් පවතී.",
    "Keep logging to understand your pattern.":
        "ඔබේ රටාව හඳුනාගැනීමට සටහන් කරන්න.",
    "Learn More →": "තවත් දැනගන්න →",
    "Next Period": "ඊළඟ ඔසප් වීම",
    "Not enabled": "සක්‍රිය කර නැත",
    "Upcoming Events": "ඉදිරි සිදුවීම්",
    "Period Start": "ඔසප් ආරම්භය",
    "Doctor Appt": "වෛද්‍ය හමුව",
    "Ovulation (est.)": "ඩිම්බ මෝචනය (ඇස්තමේන්තුව)",
    "Date Night": "හමුවීමේ සැන්දෑව",
    "Daily Care Suggestions": "දෛනික රැකවරණ යෝජනා",
    "Stay": "රැඳී සිටින්න",
    "hydrated": "ජලය ප්‍රමාණවත්ව",
    "Eat iron-rich": "යකඩ සහිත",
    "foods": "ආහාර ගන්න",
    "Try light": "සැහැල්ලු",
    "movement": "චලනය උත්සාහ කරන්න",
    "Get extra": "වැඩිපුර",
    "rest": "විවේක ගන්න",
    "Recommended Articles": "නිර්දේශිත ලිපි",
    "How to manage period cramps naturally":
        "ඔසප් කැක්කුම ස්වාභාවිකව කළමනාකරණය",
    "Iron-rich foods for your period": "ඔසප් කාලයට යකඩ සහිත ආහාර",
    "Easy exercises during your period": "ඔසප් කාලයේ පහසු ව්‍යායාම",
    "Mood changes during your cycle": "චක්‍රයේ මනෝභාව වෙනස්කම්",
    "Sample calendar · Illustrative estimates, not for contraception.":
        "ආදර්ශ දින දර්ශනය · ඇස්තමේන්තු උපත් පාලනය සඳහා නොවේ.",
    "Calendar estimates are illustrative, can be inaccurate, and must not be used for contraception.": "දින දර්ශන ඇස්තමේන්තු ආදර්ශ පමණි. ඒවා වැරදි විය හැකි අතර උපත් පාලනයට භාවිත නොකළ යුතුය.",
    "Your pace": "ඔබේ වේගය",
    "Always": "සෑම විටම",
    "Your next period in": "ඊළඟ ඔසප් වීමට",
    "Check in": "සටහන් කරන්න",
    "Your rhythm": "ඔබේ රිද්මය",
    "A little time for you": "ඔබ වෙනුවෙන් කාලයක්",
    "View Calendar": "දින දර්ශනය බලන්න",
    "Not tracked": "හඹා නොයයි",
    "Her Life. Her Way.": "ඇගේ ජීවිතය. ඇගේ මඟ.",
    "Search articles": "ලිපි සොයන්න",
    "Reminders": "මතක් කිරීම්",
    "My Profile": "මගේ පැතිකඩ",
    "You’re doing amazing!": "ඔබ ඉතා හොඳින් කරනවා!",
    "Small steps create big changes.": "කුඩා පියවර විශාල වෙනස්කම් කරයි.",
    "“A healthier, happier you\none day at a time.”":
        "“දිනෙන් දින\nවඩා සුවපත්, සතුටු ඔබක්.”",
    "Today’s Insight": "අද අවබෝධය",
    "Your energy may be slightly lower today. Try some light exercise and stay hydrated.": "අද ශක්තිය ටිකක් අඩු විය හැකිය. සැහැල්ලු ව්‍යායාම කර ප්‍රමාණවත් ජලය බොන්න.",
    "Today’s Goal": "අද ඉලක්කය",
    "Self-care time": "ස්වයං රැකවරණ කාලය",
    "Tools for Your Journey": "ඔබේ ගමනට මෙවලම්",
    "Track\nYour Cycle": "ඔබේ චක්‍රය\nසටහන් කරන්න",
    "Plan\nYour Goals": "ඔබේ ඉලක්ක\nසැලසුම් කරන්න",
    "Set\nReminders": "මතක් කිරීම්\nසකසන්න",
    "Ask\nHerly AI": "Herly AI\nවෙතින් අසන්න",
    "Your private wellbeing\ncompanion": "ඔබේ පෞද්ගලික\nසුවතා සහකාරිය",
    "Chat Now": "දැන් කතා කරන්න",
    "Need a Doctor?": "වෛද්‍යවරයෙක් අවශ්‍යද?",
    "Get trusted care quickly": "විශ්වාසනීය රැකවරණය ඉක්මනින්",
    "Online\nConsultation": "මාර්ගගත\nඋපදේශනය",
    "Nearby\nClinics": "අසල\nසායන",
    "Emergency\nSupport": "හදිසි\nසහාය",
    "Recommended for You": "ඔබට නිර්දේශිතයි",
    "Understanding your menstrual cycle": "ඔබේ ඔසප් චක්‍රය හඳුනාගැනීම",
    "Iron-rich foods for better periods": "සුවදායක ඔසප් කාලයට යකඩ සහිත ආහාර",
    "Managing stress during PMS": "ඔසප් පෙර ආතතිය කළමනාකරණය",
    "Better sleep for your cycle": "ඔබේ චක්‍රයට වඩා හොඳ නින්දක්",
    "Your space": "ඔබේ අවකාශය",
    "Everything that makes Herly yours.": "Herly ඔබේම කරන සියල්ල.",
    "Your wellbeing journey": "ඔබේ සුවතා ගමන",
    "A deeper understanding of you": "ඔබ ගැන ගැඹුරු අවබෝධයක්",
    "My Health Data": "මගේ සෞඛ්‍ය දත්ත",
    "My Goals": "මගේ ඉලක්ක",
    "Health & Wellness": "සෞඛ්‍යය හා සුවතාව",
    "My Space": "මගේ අවකාශය",
    "Learn": "ඉගෙන ගන්න",
    "Privacy & Security": "පෞද්ගලිකත්වය හා ආරක්ෂාව",
    "Safety & Support": "ආරක්ෂාව හා සහාය",
    "Help & About": "උදව් හා තොරතුරු",
    "Make Herly feel like you.": "Herly ඔබට ගැළපෙන ලෙස සකසන්න.",
    "Color story": "වර්ණ රටාව",
    "Herly Rose": "Herly රෝස",
    "Quiet Lavender": "සන්සුන් ලැවෙන්ඩර්",
    "Soft Sage": "මෘදු කොළ",
    "Light & shade": "ආලෝකය හා අඳුර",
    "Use device setting": "උපාංග සැකසුම භාවිත කරන්න",
    "Dark": "අඳුරු",
    "A little preview": "කුඩා පෙරදසුනක්",
    "A calmer space. A clearer you.": "සන්සුන් ඉඩක්. පැහැදිලි ඔබක්.",
    "Your personal theme": "ඔබේ පෞද්ගලික තේමාව",
    "Cancel": "අවලංගු කරන්න",
    "Close": "වසන්න",
    "Name": "නම",
    "Your name": "ඔබේ නම",
    "Email": "විද්‍යුත් තැපෑල",
    "Country": "රට",
    "Date of birth": "උපන් දිනය",
    "Understand my cycle": "මගේ චක්‍රය හඳුනාගන්න",
    "Feel better day-to-day": "දිනෙන් දින සුවපත් වන්න",
    "Understand my body": "මගේ සිරුර හඳුනාගන්න",
    "Self-care & beauty": "ස්වයං රැකවරණය හා රූපලාවණ්‍යය",
    "Manage stress": "ආතතිය කළමනාකරණය",
    "Sexual health": "ලිංගික සෞඛ්‍යය",
    "Trying for pregnancy": "ගැබ් ගැනීමට උත්සාහය",
    "Pregnancy": "ගර්භණීභාවය",
    "Motherhood": "මාතෘත්වය",
    "What would you like Herly to help you with?":
        "Herly ඔබට කුමකින් සහාය විය යුතුද?",
    "Create your account": "ඔබේ ගිණුම සාදන්න",
    "A few details about you": "ඔබ ගැන විස්තර කිහිපයක්",
    "Let’s understand your cycle": "ඔබේ චක්‍රය හඳුනාගනිමු",
    "Choose what matters to you. You can change this any time.":
        "ඔබට වැදගත් දේ තෝරන්න. ඕනෑම වේලාවක වෙනස් කළ හැකිය.",
    "A little space for a healthier, happier you.":
        "වඩා සුවපත්, සතුටු ඔබක් සඳහා ඉඩක්.",
    "Make this space feel like yours.": "මෙම ඉඩ ඔබේම කරගන්න.",
    "Your experience is unique. We’ll meet you where you are.":
        "ඔබේ අත්දැකීම සුවිශේෂීය. අපි ඔබ සමඟ සිටිමු.",
    "You control your data. Every permission is your choice.":
        "ඔබේ දත්ත පාලනය ඔබටයි. සෑම අවසරයක්ම ඔබේ තේරීමකි.",
    "I get my period regularly": "මට නිතිපතා ඔසප් වේ",
    "My cycle is sometimes irregular": "මගේ චක්‍රය සමහරවිට අක්‍රමවත්ය",
    "I’m not sure yet": "මට තවම නිශ්චිත නැත",
    "I don’t get periods": "මට ඔසප් නොවේ",
    "Make yourself at home": "ඔබේ අවකාශයට පිවිසෙන්න",
    "Terms & Privacy": "කොන්දේසි හා පෞද්ගලිකත්වය",
    "Biometric lock (demo)": "ජෛවමිතික අගුල (ආදර්ශ)",
    "Discreet notifications": "පුද්ගලික දැනුම්දීම්",
    "Hide sensitive modules": "සංවේදී කොටස් සඟවන්න",
    "AI personalization": "AI පුද්ගලීකරණය",
    "Enter a valid email address to continue.":
        "ඉදිරියට යාමට වලංගු විද්‍යුත් තැපෑලක් ඇතුළත් කරන්න.",
    "Please add your name, date of birth, and country.":
        "නම, උපන් දිනය හා රට එක් කරන්න.",
    "Welcome to your space. You’re all set.":
        "ඔබේ අවකාශයට සාදරයෙන් පිළිගනිමු. සියල්ල සූදානම්.",
    "Estimates are for reflection only, never for contraception or diagnosis.":
        "ඇස්තමේන්තු අවබෝධය සඳහා පමණි; උපත් පාලනයට හෝ රෝග නිර්ණයට නොවේ.",
    "For You": "ඔබ වෙනුවෙන්",
    "Cycle": "චක්‍රය",
    "Mental wellbeing": "මානසික සුවතාව",
    "Lifestyle": "ජීවන රටාව",
    "Relationships": "සබඳතා",
    "A little understanding": "කුඩා අවබෝධයක්",
    "Curiosity is a beautiful place to start.": "කුතුහලය සුන්දර ආරම්භයකි.",
    "Find something for you": "ඔබට යමක් සොයන්න",
    "No articles found. Try another search.":
        "ලිපි හමු නොවීය. වෙනත් සෙවුමක් කරන්න.",
    "Article not found": "ලිපිය හමු නොවීය",
    "Return to the library to choose an article.":
        "ලිපියක් තෝරාගැනීමට පුස්තකාලයට යන්න.",
    "Finished reading": "කියවා අවසන්",
    "Mark as read": "කියවූ ලෙස සලකුණු කරන්න",
    "Getting to know your cycle": "ඔබේ චක්‍රය හඳුනාගැනීම",
    "A softer landing at bedtime": "නින්දට සන්සුන් ආරම්භයක්",
    "Make room for yourself": "ඔබ වෙනුවෙන් ඉඩක් වෙන් කරන්න",
    "Food, culture, and everyday care": "ආහාර, සංස්කෘතිය හා දෛනික රැකවරණය",
    "Consent and boundaries": "කැමැත්ත හා සීමා",
    "A gentle reminder": "මෘදු මතක් කිරීමක්",
    "Edit reminder": "මතක් කිරීම සංස්කරණය",
    "Daily": "දිනපතා",
    "Weekdays": "සතියේ දින",
    "Weekly": "සතිපතා",
    "Edit": "සංස්කරණය",
    "Delete reminder": "මතක් කිරීම මකන්න",
    "Add a reminder": "මතක් කිරීමක් එක් කරන්න",
    "A moment for water": "ජලය සඳහා මොහොතක්",
    "Evening wind-down": "සැන්දෑවේ විවේකය",
    "Vitamins": "විටමින්",
    "Please complete your profile with a valid email.":
        "වලංගු විද්‍යුත් තැපෑලක් සමඟ පැතිකඩ සම්පූර්ණ කරන්න.",
    "Profile updated.": "පැතිකඩ යාවත්කාලීන කළා.",
    "A fresh page is waiting for you.": "නැවුම් පිටුවක් ඔබ වෙනුවෙන් ඇත.",
    "A mindful minute": "සිහියෙන් මිනිත්තුවක්",
    "A moment for you": "ඔබ වෙනුවෙන් මොහොතක්",
    "A moment outdoors": "එළිමහනේ මොහොතක්",
    "A quiet place. Just for you.": "නිහඬ ඉඩක්. ඔබටම පමණයි.",
    "A safer, happier\nyou": "වඩා ආරක්ෂිත,\nසතුටු ඔබක්",
    "About Herly": "Herly ගැන",
    "About this preview": "මෙම පෙරදසුන ගැන",
    "Add a product note": "නිෂ්පාදන සටහනක් එක් කරන්න",
    "Add a sample contact to explore this workflow.":
        "මෙම ක්‍රියාවලිය බැලීමට ආදර්ශ සබඳතාවක් එක් කරන්න.",
    "Add trusted contact": "විශ්වාසවන්ත සබඳතාවක් එක් කරන්න",
    "Advanced personal insights": "උසස් පෞද්ගලික අවබෝධ",
    "Begin a quiet moment": "නිහඬ මොහොතක් අරඹන්න",
    "Body": "සිරුර",
    "Care that fits your day.": "ඔබේ දිනයට ගැළපෙන රැකවරණය.",
    "Choose a section from More.": "තවත් වෙතින් කොටසක් තෝරන්න.",
    "Close preview": "පෙරදසුන වසන්න",
    "Configured cycle": "සැකසූ චක්‍රය",
    "Configured period": "සැකසූ ඔසප් කාලය",
    "Contextual Herly AI": "සන්දර්භගත Herly AI",
    "Copy JSON": "JSON පිටපත් කරන්න",
    "Could not load a response. Please try again.":
        "පිළිතුරක් ලබාගත නොහැකි විය. නැවත උත්සාහ කරන්න.",
    "Cycle tracking is off": "චක්‍ර හඹායෑම අක්‍රියයි",
    "Delete data": "දත්ත මකන්න",
    "Delete local demo data": "දේශීය ආදර්ශ දත්ත මකන්න",
    "Delete your local data?": "ඔබේ දේශීය දත්ත මකන්නද?",
    "Demo membership active": "ආදර්ශ සාමාජිකත්වය සක්‍රියයි",
    "Demo preview · About these insights": "ආදර්ශ පෙරදසුන · මෙම අවබෝධ ගැන",
    "Demo pricing only. No payment, subscription, or automatic renewal occurs. Premium capabilities are concept previews.": "ආදර්ශ මිල පමණි. ගෙවීම්, දායකත්ව හෝ ස්වයංක්‍රීය අලුත් කිරීම් සිදු නොවේ. උසස් පහසුකම් සංකල්ප පෙරදසුන්ය.",
    "Demo sign-in · No connection to Google or Apple is made.":
        "ආදර්ශ පිවිසුම · Google හෝ Apple වෙත සම්බන්ධ නොවේ.",
    "Demo terms & privacy": "ආදර්ශ කොන්දේසි හා පෞද්ගලිකත්වය",
    "Demo: location sharing would expire in 15 minutes. No location is accessed or shared.": "ආදර්ශය: ස්ථාන බෙදාගැනීම විනාඩි 15 කින් අවසන් වේ. ස්ථානය ලබාගන්නේ හෝ බෙදාගන්නේ නැත.",
    "Earlier": "පෙර",
    "Recent": "මෑත",
    "End demo membership": "ආදර්ශ සාමාජිකත්වය අවසන් කරන්න",
    "Enhanced personalization": "වැඩිදියුණු කළ පුද්ගලීකරණය",
    "Enter a valid email address.": "වලංගු විද්‍යුත් තැපෑලක් ඇතුළත් කරන්න.",
    "Evening skincare": "සැන්දෑ සම රැකවරණය",
    "Every rhythm\nis personal.": "සෑම රිද්මයක්ම\nපෞද්ගලිකයි.",
    "Explain my recent pattern": "මගේ මෑත රටාව පැහැදිලි කරන්න",
    "Explore Herly+ demo": "Herly+ ආදර්ශය ගවේෂණය",
    "Export copied to clipboard.": "අපනයනය පිටපත් කළා.",
    "Export my data": "මගේ දත්ත අපනයනය",
    "Feel better\nevery day": "සෑම දිනකම\nසුවපත් වන්න",
    "Finding support": "සහාය සොයාගැනීම",
    "Got it": "හරි",
    "HERLY EDITORIAL · DEMO CONTENT · 3 MIN":
        "HERLY ලිපි · ආදර්ශ අන්තර්ගතය · විනාඩි 3",
    "HERLY · HER LIFE. HER WAY.\nLocal demo · version 1.0":
        "HERLY · ඇගේ ජීවිතය. ඇගේ මඟ.\nදේශීය ආදර්ශය · අනුවාදය 1.0",
    "Hair care": "හිසකෙස් රැකවරණය",
    "Herly is a local prototype. Entries are stored on this device using unencrypted app preferences. Use sample information only. No account is created and no medical service is provided.": "Herly දේශීය මූලාකෘතියකි. සටහන් මෙම උපාංගයේ සංකේතනය නොකළ සැකසුම්වල සුරැකේ. ආදර්ශ තොරතුරු පමණක් භාවිත කරන්න. ගිණුමක් සෑදීම හෝ වෛද්‍ය සේවාවක් සැපයීම සිදු නොවේ.",
    "Herly+ demo activated. No charge was made.":
        "Herly+ ආදර්ශය සක්‍රියයි. ගාස්තුවක් අය නොවීය.",
    "Herly · Her Life. Her Way.": "Herly · ඇගේ ජීවිතය. ඇගේ මඟ.",
    "Herly. Her Life. Her Way.": "Herly. ඇගේ ජීවිතය. ඇගේ මඟ.",
    "Herly. Her Life. Her Way. Loading your welcome screen.":
        "Herly. ඇගේ ජීවිතය. ඇගේ මඟ. පිළිගැනීමේ තිරය පූරණය වේ.",
    "Hi, I’m Herly. A little space to ask, reflect, and feel heard. How can I help today?": "ආයුබෝවන්, මම Herly. අසන්නට, සිතන්නට හා සවන් ලැබෙන්නට ඉඩක්. අද මම කෙසේ උදව් කරන්නද?",
    "ILLUSTRATIVE DEMO CHART": "ආදර්ශ ප්‍රස්තාරය",
    "If you are in immediate danger, contact your local emergency services. This prototype does not make calls, send messages, or share location.": "ඔබ හදිසි අනතුරක නම් දේශීය හදිසි සේවාවන් අමතන්න. මෙම මූලාකෘතිය ඇමතුම්, පණිවිඩ හෝ ස්ථාන බෙදාගැනීම් සිදු නොකරයි.",
    "Keep data": "දත්ත තබාගන්න",
    "Latest entry": "නවතම සටහන",
    "Log a few check-ins to see your own observations.":
        "ඔබේ නිරීක්ෂණ බැලීමට සටහන් කිහිපයක් එක් කරන්න.",
    "Log a skin observation": "සම පිළිබඳ නිරීක්ෂණයක් සටහන් කරන්න",
    "Longer history & reports": "දිගු ඉතිහාසය හා වාර්තා",
    "More room for your story.": "ඔබේ කතාවට වැඩි ඉඩක්.",
    "Morning skincare": "උදෑසන සම රැකවරණය",
    "Name and phone": "නම හා දුරකථනය",
    "Nothing logged yet. Start with how you feel.":
        "තවම සටහන් නැත. ඔබේ හැඟීමෙන් පටන් ගන්න.",
    "Notice. Reflect.\nUnderstand.": "නිරීක්ෂණය කරන්න. සිතන්න.\nතේරුම් ගන්න.",
    "Nov 15": "නොවැ 15",
    "Nov 2 – 6": "නොවැ 2 – 6",
    "Nov 2 – Nov 6": "නොවැ 2 – නොවැ 6",
    "Nov 24": "නොවැ 24",
    "Nov 4": "නොවැ 4",
    "Nov 4 (est.)": "නොවැ 4 (ඇස්ත.)",
    "Oct 27": "ඔක් 27",
    "Oct 31": "ඔක් 31",
    "Nutrition and energy": "පෝෂණය හා ශක්තිය",
    "Open selected calendar date": "තෝරාගත් දිනය විවෘත කරන්න",
    "PIN preview": "PIN පෙරදසුන",
    "PIN preview complete. No lock is enabled.":
        "PIN පෙරදසුන අවසන්. අගුලක් සක්‍රිය නැත.",
    "Patterns to reflect on. A story only you can tell.":
        "සිතා බැලීමට රටා. ඔබටම පැවසිය හැකි කතාවක්.",
    "Pause. Notice your surroundings. Give yourself a little room to breathe.":
        "නවතින්න. අවට බලන්න. හුස්ම ගැනීමට ඔබට ඉඩක් දෙන්න.",
    "Personalized responses are turned off. You can choose whether to enable them in Privacy & Security.": "පුද්ගලික පිළිතුරු අක්‍රියයි. පෞද්ගලිකත්වය හා ආරක්ෂාව වෙතින් සක්‍රිය කළ හැකිය.",
    "Photo storage is a demo placeholder.":
        "ඡායාරූප ගබඩා කිරීම ආදර්ශ පහසුකමකි.",
    "Photo upload preview": "ඡායාරූප උඩුගත කිරීමේ පෙරදසුන",
    "Premium routines": "උසස් දිනචර්යා",
    "Preview": "පෙරදසුන",
    "Preview a safety check-in": "ආරක්ෂක පණිවිඩ පෙරදසුන",
    "Preview temporary location sharing": "තාවකාලික ස්ථාන බෙදාගැනීමේ පෙරදසුන",
    "Progress photos": "ප්‍රගති ඡායාරූප",
    "Prototype privacy: data stays in this browser or device, in unencrypted local storage. Biometrics and notifications are interface demos.": "මූලාකෘති පෞද්ගලිකත්වය: දත්ත මෙම බ්‍රව්සරයේ හෝ උපාංගයේ සංකේතනය නොකළ ගබඩාවේ පවතී. ජෛවමිතික හා දැනුම්දීම් අතුරුමුහුණත් ආදර්ශ වේ.",
    "Quick check-in": "ඉක්මන් සටහන",
    "Reach out to a trusted person, a qualified healthcare professional, or a local support organization. For urgent assistance, use the emergency services available in your location.": "විශ්වාසවන්ත අයෙකු, සුදුසුකම් ලත් සෞඛ්‍ය වෘත්තිකයෙකු හෝ දේශීය සහාය ආයතනයක් අමතන්න. හදිසි සහායට ඔබේ ප්‍රදේශයේ හදිසි සේවාවන් භාවිත කරන්න.",
    "Reflection": "ආවර්ජනය",
    "Remove contact": "සබඳතාව ඉවත් කරන්න",
    "Safety check-in preview": "ආරක්ෂක පණිවිඩ පෙරදසුන",
    "Save a reflection": "ආවර්ජනය සුරකින්න",
    "Set demo PIN": "ආදර්ශ PIN සකසන්න",
    "Small nudges, on your terms. Scheduling is a demo; no notifications are sent.":
        "ඔබට ගැළපෙන මතක් කිරීම්. කාලසටහන ආදර්ශයකි; දැනුම්දීම් නොයවයි.",
    "Small steps. A little more balance.": "කුඩා පියවර. තවත් සමබරතාවයක්.",
    "Sri Lanka": "ශ්‍රී ලංකාව",
    "Take this moment at your own pace.": "මෙම මොහොත ඔබේ වේගයෙන් ගන්න.",
    "There is no one right journey.": "සැමට එකම නිවැරදි ගමනක් නැත.",
    "This care directory is a design preview. No provider search, location access, or booking takes place.": "මෙම සේවා ලැයිස්තුව සැලසුම් පෙරදසුනකි. සැපයුම්කරුවන් සෙවීම, ස්ථාන ප්‍රවේශය හෝ වෙන්කිරීම් සිදු නොවේ.",
    "This chart uses sample values to demonstrate the design. Your saved entries appear below. No medical correlations or diagnoses are inferred.": "මෙම ප්‍රස්තාරය ආදර්ශ අගයන් භාවිත කරයි. සුරැකි සටහන් පහතින් ඇත. වෛද්‍ය සම්බන්ධතා හෝ රෝග නිර්ණයන් අනුමාන නොකරයි.",
    "This removes your profile, logs, chats, and preferences from this demo. This cannot be undone.": "මෙය ඔබේ පැතිකඩ, සටහන්, කතාබහ හා සැකසුම් මකයි. මෙය ආපසු හැරවිය නොහැකිය.",
    "Tips for better sleep": "හොඳ නින්දට උපදෙස්",
    "Today, I’m grateful for…": "අද මම කෘතඥ වන්නේ…",
    "Trusted contact (demo)": "විශ්වාසවන්ත සබඳතාව (ආදර්ශ)",
    "Trusted people": "විශ්වාසවන්ත පුද්ගලයන්",
    "Tue, 28 Oct 2026": "2026 ඔක්තෝබර් 28",
    "Understand\nyour body": "ඔබේ සිරුර\nහඳුනාගන්න",
    "Understand yourself\nmore deeply.": "ඔබ ගැන\nගැඹුරින් දැනගන්න.",
    "Version 1.0.0 · Made with care": "අනුවාදය 1.0.0 · සැලකිල්ලෙන් නිමවූ",
    "Voice note · demo": "හඬ සටහන · ආදර්ශ",
    "Voice recording is a demo placeholder.": "හඬ පටිගත කිරීම ආදර්ශ පහසුකමකි.",
    "What’s on your mind?": "ඔබේ සිතේ මොනවාද?",
    "Write a little something first.": "පළමුව යමක් ලියන්න.",
    "You decide what to share. Always.": "බෙදාගන්නා දේ තීරණය ඔබේය. සැමවිටම.",
    "You deserve to feel safe and supported.":
        "ආරක්ෂාව හා සහාය ලැබීමට ඔබ සුදුසුය.",
    "Your daily ritual": "ඔබේ දෛනික චාරිත්‍රය",
    "Your data export": "ඔබේ දත්ත අපනයනය",
    "Your energy may be slightly lower today.\nTry some light exercise and stay hydrated.": "අද ශක්තිය ටිකක් අඩු විය හැකිය.\nසැහැල්ලු ව්‍යායාම කර ප්‍රමාණවත් ජලය බොන්න.",
    "Your entries": "ඔබේ සටහන්",
    "Your observations": "ඔබේ නිරීක්ෂණ",
    "Your observations, together in one place.": "ඔබේ නිරීක්ෂණ එකම තැනක.",
    "Your patterns start here": "ඔබේ රටා මෙතැනින් ඇරඹේ",
    "Your reflection is saved.": "ඔබේ ආවර්ජනය සුරැකිණි.",
    "Your reflections": "ඔබේ ආවර්ජන",
    "Your story starts with a check-in. A few moments today can help you notice your own patterns.":
        "ඔබේ කතාව සටහනකින් ඇරඹේ. අද මොහොතක් ඔබේ රටා හඳුනාගැනීමට උපකාරී වේ.",
    "4 digits · not stored": "ඉලක්කම් 4 · සුරැකෙන්නේ නැත",
    "glasses (0–30)": "වීදුරු (0–30)",
    "hours (0–24)": "පැය (0–24)",
    "kg (1–500)": "කිලෝග්‍රෑම් (1–500)",
    "minutes (0–1440)": "විනාඩි (0–1440)",
    "steps (0–100000)": "පියවර (0–100000)",
    "Annual · LKR 4,900 / year": "වාර්ෂික · වසරකට රු. 4,900",
    "Monthly · LKR 590 / month": "මාසික · මසකට රු. 590",
    "3 min read · Demo content →": "විනාඩි 3 කියවීම · ආදර්ශ අන්තර්ගතය →",
    "A gentle evening routine can be a useful place to start. Try a consistent wind-down time, a comfortable room, and a few quiet minutes away from screens. What helps you feel settled?": "මෘදු සැන්දෑ දිනචර්යාවක් හොඳ ආරම්භයකි. නිතිපතා විවේක කාලයක්, සුවපහසු කාමරයක් හා තිරවලින් ඈත් වූ නිහඬ මිනිත්තු කිහිපයක් උත්සාහ කරන්න. ඔබට සන්සුන් වීමට උදව් වන්නේ කුමක්ද?",
    "I can help you record when discomfort happens and prepare questions for a clinician. This is a simulated conversation, not a diagnosis. Severe, unusual, or worsening pain deserves professional attention.": "අපහසුතාව ඇති වේලාව සටහන් කිරීමටත් වෛද්‍යවරයෙකුට ප්‍රශ්න සකස් කිරීමටත් මට උදව් කළ හැකිය. මෙය ආදර්ශ කතාබහක් මිස රෝග නිර්ණයක් නොවේ. දැඩි, අසාමාන්‍ය හෝ වැඩිවන වේදනාවට වෘත්තීය උපදෙස් ලබාගන්න.",
    "That sounds difficult. You could take a quiet moment and notice what is around you, or reach out to someone you trust. Would you like to write down how you feel?": "එය අපහසු බව පෙනේ. නිහඬ මොහොතක් ගෙන අවට නිරීක්ෂණය කරන්න, නැතහොත් විශ්වාසවන්ත අයෙකු අමතන්න. ඔබේ හැඟීම් ලියා තැබීමට කැමතිද?",
    "Your demo history includes several mood and sleep entries. These are examples, not a medical finding. Keep logging what you notice to build a more useful personal record.": "ආදර්ශ ඉතිහාසයේ මනෝභාව හා නින්ද සටහන් කිහිපයක් ඇත. මේවා උදාහරණ මිස වෛද්‍ය සොයාගැනීම් නොවේ. වඩා ප්‍රයෝජනවත් වාර්තාවක් සඳහා ඔබේ නිරීක්ෂණ සටහන් කරන්න.",
    "Thank you for sharing. I’m a demo wellbeing companion with scripted replies. You can use your journal to reflect, log how you feel, or explore the learning library. What would feel useful today?": "බෙදාගත්තාට ස්තුතියි. මම පෙර සකස් කළ පිළිතුරු දෙන ආදර්ශ සුවතා සහකාරියක්. දිනපොතේ සිතිවිලි ලියන්න, හැඟීම් සටහන් කරන්න හෝ පුස්තකාලය බලන්න. අද ඔබට ප්‍රයෝජනවත් වන්නේ කුමක්ද?",
    "SAFETY: This demo cannot assess urgent symptoms or provide crisis care. If you may be in immediate danger, contact local emergency services or a trusted person now. Seek professional help promptly for severe or worsening symptoms.": "ආරක්ෂාව: මෙම ආදර්ශයට හදිසි ලක්ෂණ ඇගයීමට හෝ අර්බුද රැකවරණය සැපයීමට නොහැකිය. හදිසි අනතුරක් විය හැකි නම් දේශීය හදිසි සේවා හෝ විශ්වාසවන්ත අයෙකු දැන් අමතන්න. දැඩි හෝ වැඩිවන ලක්ෂණ සඳහා වහාම වෘත්තීය සහාය ලබාගන්න.",
    "I’m sorry to hear you’re feeling more tired 💜":
        "ඔබට වැඩි විඩාවක් දැනීම ගැන කනගාටුයි 💜",
    "Energy can change for many reasons. Recording how you feel alongside your cycle can help you notice patterns. This sample conversation cannot determine the cause.": "බොහෝ හේතු නිසා ශක්තිය වෙනස් විය හැකිය. චක්‍රය සමඟ හැඟීම් සටහන් කිරීම රටා හඳුනාගැනීමට උපකාරී වේ. මෙම ආදර්ශ කතාබහට හේතුව තීරණය කළ නොහැකිය.",
    "Here are a few gentle things that may help:":
        "උපකාරී විය හැකි මෘදු පියවර කිහිපයක්:",
    "💧  Stay hydrated": "💧  ප්‍රමාණවත් ජලය බොන්න",
    "🌿  Try light movement like a short walk":
        "🌿  කෙටි ඇවිදීමක් වැනි සැහැල්ලු චලනයක් කරන්න",
    "🌙  Get a little extra rest": "🌙  තවත් ටිකක් විවේක ගන්න",
    "💗  Include iron-rich foods in your meals":
        "💗  ආහාරවලට යකඩ සහිත දේ එක් කරන්න",
    "Everyone’s experience is different. If your fatigue feels severe or continues, speak with a doctor.": "සෑම කෙනෙකුගේම අත්දැකීම වෙනස්ය. විඩාව දැඩි නම් හෝ දිගටම පවතී නම් වෛද්‍යවරයෙකු හමුවන්න.",
    "Your cycle is a personal pattern, and it can change. Recording dates and observations can help you describe your experience.": "ඔබේ චක්‍රය පෞද්ගලික රටාවකි; එය වෙනස් විය හැකිය. දින හා නිරීක්ෂණ සටහන් කිරීම ඔබේ අත්දැකීම පැහැදිලි කිරීමට උපකාරී වේ.",
    "Try noting the first day of bleeding, how you feel, and anything you want to discuss with a clinician. Estimates in Herly are illustrative and are not suitable for contraception.": "රුධිර වහනයේ පළමු දිනය, ඔබේ හැඟීම හා වෛද්‍යවරයෙකු සමඟ සාකච්ඡා කිරීමට ඇති දේ සටහන් කරන්න. Herly ඇස්තමේන්තු ආදර්ශ පමණි; උපත් පාලනයට සුදුසු නැත.",
    "Reflection: what would you like to understand about your own pattern?":
        "ආවර්ජනය: ඔබේ රටාව ගැන ඔබට දැනගැනීමට අවශ්‍ය කුමක්ද?",
    "An evening ritual can be as simple as a few quiet minutes. Choose something that feels comfortable and repeatable.": "සැන්දෑ චාරිත්‍රයක් නිහඬ මිනිත්තු කිහිපයක් තරම් සරල විය හැකිය. පහසු හා නැවත කළ හැකි දෙයක් තෝරන්න.",
    "Write down tomorrow’s priorities, put your phone aside, and make space to rest. This is illustrative wellness content, not clinical advice.": "හෙට ප්‍රමුඛතා ලියන්න, දුරකථනය පසෙක තබා විවේකයට ඉඩ දෙන්න. මෙය ආදර්ශ සුවතා අන්තර්ගතයක් මිස සායනික උපදෙස් නොවේ.",
    "Self-care does not need a perfect routine. Pick one small action that feels kind today.": "ස්වයං රැකවරණයට පරිපූර්ණ දිනචර්යාවක් අවශ්‍ය නැත. අද ඔබට කාරුණික කුඩා ක්‍රියාවක් තෝරන්න.",
    "A short walk, a favourite song, or a moment with your journal can be your starting point.": "කෙටි ඇවිදීමක්, ප්‍රියතම ගීතයක් හෝ දිනපොත සමඟ මොහොතක් ආරම්භයක් විය හැකිය.",
    "Use this demo journal to notice meals you enjoy and questions you have about nutrition.": "ඔබ කැමති ආහාර හා පෝෂණය ගැන ප්‍රශ්න සටහන් කිරීමට මෙම ආදර්ශ දිනපොත භාවිත කරන්න.",
    "For personalized dietary guidance, speak with a qualified professional. Herly’s learning library is sample content.": "පුද්ගලික ආහාර උපදෙස් සඳහා සුදුසුකම් ලත් වෘත්තිකයෙකු අමතන්න. Herly පුස්තකාලයේ ඇත්තේ ආදර්ශ අන්තර්ගතයකි.",
    "Your boundaries matter. You can change your mind, ask for time, and choose what feels comfortable.": "ඔබේ සීමා වැදගත්ය. ඔබට අදහස වෙනස් කිරීමට, කාලය ඉල්ලීමට හා පහසු දේ තෝරාගැනීමට හැකිය.",
    "Healthy conversations leave room for mutual respect and a clear, freely given choice.": "සෞඛ්‍ය සම්පන්න කතාබහ අන්‍යෝන්‍ය ගෞරවයට හා නිදහස් පැහැදිලි තේරීමට ඉඩ දෙයි.",
    "Your privacy, made clear": "ඔබේ පෞද්ගලිකත්වය පැහැදිලිව",
    "This prototype stores sample data on this device in unencrypted app preferences. No backend or live AI receives your entries. Biometrics and PIN are demonstrations, not security protections.": "මෙම මූලාකෘතිය ආදර්ශ දත්ත උපාංගයේ සංකේතනය නොකළ සැකසුම්වල සුරකියි. සේවාදායකයක් හෝ සජීවී AI ඔබේ සටහන් නොලබයි. ජෛවමිතික හා PIN ආදර්ශ මිස ආරක්ෂක විධි නොවේ.",
    "“I’d appreciate a check-in. Could you contact me?”":
        "“මගේ තත්ත්වය විමසනවා නම් අගය කරනවා. මාව අමතන්න පුළුවන්ද?”",
    "Demo only. Nothing is sent.": "ආදර්ශයක් පමණි. කිසිවක් නොයවයි.",
    "Unlogged metrics, fertility dates, and the daily insight are sample content from the design reference. They are not personalized medical predictions. Saved check-ins replace the corresponding sample metric. Do not use cycle estimates for contraception. Doctor services are visual previews.": "සටහන් නොකළ අගයන්, සරු දින හා දෛනික අවබෝධය සැලසුමේ ආදර්ශ අන්තර්ගත වේ. ඒවා පුද්ගලික වෛද්‍ය අනාවැකි නොවේ. සුරැකි සටහන් අදාළ ආදර්ශ අගය වෙනස් කරයි. චක්‍ර ඇස්තමේන්තු උපත් පාලනයට භාවිත නොකරන්න. වෛද්‍ය සේවා දෘශ්‍ය පෙරදසුන්ය.",
    "Herly is a runnable Flutter design prototype for a personal wellbeing companion.": "Herly පෞද්ගලික සුවතා සහකාරියක් සඳහා ක්‍රියාත්මක Flutter සැලසුම් මූලාකෘතියකි.",
    "Tracking, preferences, reminders, and chat history are saved locally. Authentication, AI, subscriptions, security locks, notifications, and safety actions are simulations.": "සටහන්, සැකසුම්, මතක් කිරීම් හා කතාබහ ඉතිහාසය දේශීයව සුරැකේ. පිවිසුම, AI, දායකත්ව, අගුල්, දැනුම්දීම් හා ආරක්ෂක ක්‍රියා ආදර්ශ වේ.",
    "English, Sinhala and Tamil interface text changes with your language setting. Your own notes and messages stay as you wrote them.": "භාෂා සැකසුම අනුව ඉංග්‍රීසි, සිංහල හා දෙමළ අතුරුමුහුණත් පෙළ වෙනස් වේ. ඔබේ සටහන් හා පණිවිඩ ඔබ ලියූ ලෙසම පවතී.",
    "Use sample data only. This prototype does not provide diagnosis or emergency services.": "ආදර්ශ දත්ත පමණක් භාවිත කරන්න. මෙම මූලාකෘතිය රෝග නිර්ණය හෝ හදිසි සේවා සපයන්නේ නැත.",
    "Track Your Cycle": "ඔබේ චක්‍රය සටහන් කරන්න",
    "Plan Your Goals": "ඔබේ ඉලක්ක සැලසුම් කරන්න",
    "Set Reminders": "මතක් කිරීම් සකසන්න",
    "Ask Herly AI": "Herly AI වෙතින් අසන්න",
    "Online Consultation": "මාර්ගගත උපදේශනය",
    "Nearby Clinics": "අසල සායන",
    "Emergency Support": "හදිසි සහාය",
  },
  "ta": {
    "Text size": "உரை அளவு",
    "Font size": "எழுத்துரு அளவு",
    "Adjust text across the app. Your device accessibility setting is also respected.": "செயலி முழுவதும் உரை அளவை மாற்றுங்கள். சாதனத்தின் அணுகல்தன்மை அமைப்பும் பின்பற்றப்படும்.",
    "Reset text size": "உரை அளவை மீட்டமை",

    "Home": "முகப்பு",
    "Calendar": "நாட்காட்டி",
    "Insights": "நுண்ணறிவு",
    "More": "மேலும்",
    "Chat": "அரட்டை",
    "Get Started": "தொடங்குங்கள்",
    "Welcome to": "வரவேற்கிறோம்",
    "Your personal companion for every stage of your journey.":
        "உங்கள் பயணத்தின் ஒவ்வொரு நிலையிலும் உங்கள் துணை.",
    "I already have an account": "எனக்கு ஏற்கனவே கணக்கு உள்ளது",
    "Continue": "தொடரவும்",
    "Save": "சேமி",
    "Language": "மொழி",
    "Appearance": "தோற்றம்",
    "Good morning": "காலை வணக்கம்",
    "How are you feeling?": "நீங்கள் எப்படி உணர்கிறீர்கள்?",
    "Log Period": "மாதவிடாயைப் பதிவு செய்",
    "Today": "இன்று",
    "Settings": "அமைப்புகள்",
    "Your privacy is our priority": "உங்கள் தனியுரிமையே எங்கள் முன்னுரிமை",
    "Period": "மாதவிடாய்",
    "Symptoms": "அறிகுறிகள்",
    "Mood": "மனநிலை",
    "Sleep": "தூக்கம்",
    "Water": "தண்ணீர்",
    "Exercise": "உடற்பயிற்சி",
    "Nutrition": "ஊட்டச்சத்து",
    "Weight": "எடை",
    "Self-Care": "சுய பராமரிப்பு",
    "Energy": "ஆற்றல்",
    "Steps": "நடைகள்",
    "Medication": "மருந்து",
    "Skin": "சருமம்",
    "Journal": "நாட்குறிப்பு",
    "Cramps": "பிடிப்புகள்",
    "Headache": "தலைவலி",
    "Bloating": "வயிற்று உப்புசம்",
    "Mood changes": "மனநிலை மாற்றங்கள்",
    "Acne": "முகப்பரு",
    "Fatigue": "சோர்வு",
    "Breast tenderness": "மார்பக வலி",
    "Cravings": "உணவு விருப்பங்கள்",
    "Back pain": "முதுகுவலி",
    "Light": "லேசான",
    "Medium": "மிதமான",
    "Heavy": "அதிகமான",
    "Spotting": "சிறு இரத்தக்கசிவு",
    "Great": "மிக நன்று",
    "Good": "நன்று",
    "Okay": "பரவாயில்லை",
    "Low": "குறைவு",
    "Anxious": "பதட்டம்",
    "High": "அதிகம்",
    "Steady": "சீரான",
    "Clear": "தெளிவு",
    "Dry": "வறண்ட",
    "Oily": "எண்ணெய்ப்பசை",
    "Sensitive": "உணர்திறன்",
    "Entry": "பதிவு",
    "Your entry": "உங்கள் பதிவு",
    "Notes (optional)": "குறிப்புகள் (விருப்பம்)",
    "A little space for how you feel…": "உங்கள் உணர்வுகளுக்கு ஓர் இடம்…",
    "Add an entry before saving.": "சேமிக்கும் முன் பதிவைச் சேர்க்கவும்.",
    "Could not save. Please try again.":
        "சேமிக்க முடியவில்லை. மீண்டும் முயலவும்.",
    "Close tracker": "பதிவுப் பலகையை மூடு",
    "See All": "அனைத்தையும் காண்க",
    "Your private wellbeing companion": "உங்கள் தனிப்பட்ட நல்வாழ்வுத் துணை",
    "Hi": "வணக்கம்",
    "I’m Herly AI, here to listen, answer your questions and support you on your journey.": "நான் Herly AI. உங்களைக் கேட்கவும், கேள்விகளுக்குப் பதிலளிக்கவும், உங்கள் பயணத்தில் உதவவும் இருக்கிறேன்.",
    "Ask anything": "எதையும் கேளுங்கள்",
    "Get personalized insights": "தனிப்பட்ட நுண்ணறிவைப் பெறுங்கள்",
    "Practical tips & guidance": "நடைமுறை ஆலோசனைகள்",
    "Safe & private space": "பாதுகாப்பான தனிப்பட்ட இடம்",
    "Your conversations stay on this device. Demo replies.":
        "உங்கள் உரையாடல்கள் இச்சாதனத்தில் இருக்கும். மாதிரி பதில்கள்.",
    "I’ve been feeling more tired than usual this week. Any ideas why?":
        "இந்த வாரம் வழக்கத்தைவிட சோர்வாக இருக்கிறேன். ஏன் என்று தெரியுமா?",
    "Herly is typing…": "Herly எழுதுகிறது…",
    "You might also like to ask:": "நீங்கள் இதையும் கேட்கலாம்:",
    "How can I improve my sleep?": "என் தூக்கத்தை மேம்படுத்துவது எப்படி?",
    "What foods boost my energy?": "எந்த உணவுகள் ஆற்றலை அதிகரிக்கும்?",
    "Is my period coming soon?": "என் மாதவிடாய் விரைவில் வருமா?",
    "Ask Herly anything…": "Herlyயிடம் எதையும் கேளுங்கள்…",
    "Sample conversation": "மாதிரி உரையாடல்",
    "Sent": "அனுப்பப்பட்டது",
    "Demo response": "மாதிரி பதில்",
    "Helpful": "பயனுள்ளது",
    "Not helpful": "பயனில்லை",
    "Copy response": "பதிலை நகலெடு",
    "Response copied.": "பதில் நகலெடுக்கப்பட்டது.",
    "Open support resources": "உதவி வளங்களைத் திற",
    "Back to Home": "முகப்பிற்குச் செல்",
    "Conversation history": "உரையாடல் வரலாறு",
    "Your conversations will appear here.":
        "உங்கள் உரையாடல்கள் இங்கு தோன்றும்.",
    "Chat settings": "அரட்டை அமைப்புகள்",
    "More suggestions": "மேலும் பரிந்துரைகள்",
    "Attachments (demo)": "இணைப்புகள் (மாதிரி)",
    "Attachments are a demo placeholder.": "இணைப்புகள் ஒரு மாதிரி வசதி.",
    "Voice (demo)": "குரல் (மாதிரி)",
    "Voice input is a demo placeholder.": "குரல் உள்ளீடு ஒரு மாதிரி வசதி.",
    "Send message": "செய்தியை அனுப்பு",
    "Choose date": "தேதியைத் தேர்ந்தெடு",
    "Calendar settings": "நாட்காட்டி அமைப்புகள்",
    "Previous month": "முந்தைய மாதம்",
    "Next month": "அடுத்த மாதம்",
    "Fertile Window": "கருவுறும் காலம்",
    "Fertile window": "கருவுறும் காலம்",
    "Ovulation": "அண்டவிடுப்பு",
    "Special Day": "சிறப்பு நாள்",
    "Notes": "குறிப்புகள்",
    "Demo": "மாதிரி",
    "Selected day": "தேர்ந்தெடுத்த நாள்",
    "Next day": "அடுத்த நாள்",
    "Your daily wellbeing": "உங்கள் தினசரி நல்வாழ்வு",
    "Take it easy and be kind to yourself.":
        "ஓய்வெடுத்து உங்களிடம் அன்பாக இருங்கள்.",
    "Flow": "இரத்தப்போக்கு",
    "Mild": "லேசான",
    "Calm": "அமைதி",
    "Not logged": "பதியப்படவில்லை",
    "Log Today": "இன்றைய பதிவு",
    "Today’s Insights": "இன்றைய நுண்ணறிவு",
    "Your energy may be lower today. Try gentle movement, stay hydrated and consider iron-rich foods.": "இன்று ஆற்றல் குறையலாம். மென்மையான இயக்கம், போதிய தண்ணீர் மற்றும் இரும்புச்சத்து உணவுகளைக் கருத்தில் கொள்ளுங்கள்.",
    "Cycle Phase": "சுழற்சி நிலை",
    "Menstrual Phase": "மாதவிடாய் நிலை",
    "Your cycle": "உங்கள் சுழற்சி",
    "Your period has started. This phase usually lasts 3–7 days.":
        "மாதவிடாய் தொடங்கியுள்ளது. இந்நிலை பொதுவாக 3–7 நாட்கள் நீடிக்கும்.",
    "Keep logging to understand your pattern.":
        "உங்கள் முறையை அறிய தொடர்ந்து பதியுங்கள்.",
    "Learn More →": "மேலும் அறிக →",
    "Next Period": "அடுத்த மாதவிடாய்",
    "Not enabled": "இயக்கப்படவில்லை",
    "Upcoming Events": "வரவிருக்கும் நிகழ்வுகள்",
    "Period Start": "மாதவிடாய் தொடக்கம்",
    "Doctor Appt": "மருத்துவர் சந்திப்பு",
    "Ovulation (est.)": "அண்டவிடுப்பு (மதிப்பீடு)",
    "Date Night": "சந்திப்பு இரவு",
    "Daily Care Suggestions": "தினசரி பராமரிப்பு யோசனைகள்",
    "Stay": "இருங்கள்",
    "hydrated": "நீர்ச்சத்துடன்",
    "Eat iron-rich": "இரும்புச்சத்துள்ள",
    "foods": "உணவுகள்",
    "Try light": "மென்மையான",
    "movement": "இயக்கம்",
    "Get extra": "கூடுதல்",
    "rest": "ஓய்வு",
    "Recommended Articles": "பரிந்துரைக்கப்பட்ட கட்டுரைகள்",
    "How to manage period cramps naturally":
        "மாதவிடாய் பிடிப்புகளை இயற்கையாக சமாளிப்பது",
    "Iron-rich foods for your period": "மாதவிடாய்க்கான இரும்புச்சத்து உணவுகள்",
    "Easy exercises during your period": "மாதவிடாயின்போது எளிய பயிற்சிகள்",
    "Mood changes during your cycle": "சுழற்சியின்போது மனநிலை மாற்றங்கள்",
    "Sample calendar · Illustrative estimates, not for contraception.":
        "மாதிரி நாட்காட்டி · மதிப்பீடுகள் கருத்தடைக்கானவை அல்ல.",
    "Calendar estimates are illustrative, can be inaccurate, and must not be used for contraception.": "நாட்காட்டி மதிப்பீடுகள் விளக்கத்திற்கானவை; தவறாக இருக்கலாம். கருத்தடைக்குப் பயன்படுத்தக்கூடாது.",
    "Your pace": "உங்கள் வேகம்",
    "Always": "எப்போதும்",
    "Your next period in": "அடுத்த மாதவிடாய்க்கு",
    "Check in": "பதிவு செய்",
    "Your rhythm": "உங்கள் தாளம்",
    "A little time for you": "உங்களுக்காகச் சிறிது நேரம்",
    "View Calendar": "நாட்காட்டியைக் காண்க",
    "Not tracked": "கண்காணிக்கப்படவில்லை",
    "Her Life. Her Way.": "அவள் வாழ்க்கை. அவள் வழி.",
    "Search articles": "கட்டுரைகளைத் தேடு",
    "Reminders": "நினைவூட்டல்கள்",
    "My Profile": "என் சுயவிவரம்",
    "You’re doing amazing!": "நீங்கள் அருமையாகச் செய்கிறீர்கள்!",
    "Small steps create big changes.":
        "சிறிய அடிகள் பெரிய மாற்றங்களை உருவாக்கும்.",
    "“A healthier, happier you\none day at a time.”":
        "“ஒவ்வொரு நாளும்\nஆரோக்கியமும் மகிழ்ச்சியும்.”",
    "Today’s Insight": "இன்றைய நுண்ணறிவு",
    "Your energy may be slightly lower today. Try some light exercise and stay hydrated.": "இன்று ஆற்றல் சற்று குறையலாம். லேசாக உடற்பயிற்சி செய்து தண்ணீர் அருந்துங்கள்.",
    "Today’s Goal": "இன்றைய இலக்கு",
    "Self-care time": "சுய பராமரிப்பு நேரம்",
    "Tools for Your Journey": "உங்கள் பயணத்திற்கான கருவிகள்",
    "Track\nYour Cycle": "உங்கள் சுழற்சியை\nகண்காணிக்கவும்",
    "Plan\nYour Goals": "உங்கள் இலக்குகளை\nதிட்டமிடுங்கள்",
    "Set\nReminders": "நினைவூட்டல்களை\nஅமையுங்கள்",
    "Ask\nHerly AI": "Herly AIயிடம்\nகேளுங்கள்",
    "Your private wellbeing\ncompanion": "உங்கள் தனிப்பட்ட\nநல்வாழ்வுத் துணை",
    "Chat Now": "இப்போது பேசுங்கள்",
    "Need a Doctor?": "மருத்துவர் தேவையா?",
    "Get trusted care quickly": "நம்பகமான பராமரிப்பை விரைவில் பெறுங்கள்",
    "Online\nConsultation": "இணைய\nஆலோசனை",
    "Nearby\nClinics": "அருகிலுள்ள\nமருத்துவமனைகள்",
    "Emergency\nSupport": "அவசர\nஉதவி",
    "Recommended for You": "உங்களுக்கான பரிந்துரைகள்",
    "Understanding your menstrual cycle": "உங்கள் மாதவிடாய் சுழற்சியை அறிதல்",
    "Iron-rich foods for better periods":
        "சீரான மாதவிடாய்க்கு இரும்புச்சத்து உணவுகள்",
    "Managing stress during PMS": "மாதவிடாய்க்கு முன் மனஅழுத்தத்தை கையாளுதல்",
    "Better sleep for your cycle": "உங்கள் சுழற்சிக்குச் சிறந்த தூக்கம்",
    "Your space": "உங்கள் இடம்",
    "Everything that makes Herly yours.":
        "Herlyயை உங்களுடையதாக்கும் அனைத்தும்.",
    "Your wellbeing journey": "உங்கள் நல்வாழ்வுப் பயணம்",
    "A deeper understanding of you": "உங்களைப் பற்றிய ஆழமான புரிதல்",
    "My Health Data": "என் சுகாதாரத் தரவு",
    "My Goals": "என் இலக்குகள்",
    "Health & Wellness": "ஆரோக்கியமும் நல்வாழ்வும்",
    "My Space": "என் இடம்",
    "Learn": "கற்றுக்கொள்",
    "Privacy & Security": "தனியுரிமையும் பாதுகாப்பும்",
    "Safety & Support": "பாதுகாப்பும் ஆதரவும்",
    "Help & About": "உதவியும் விவரமும்",
    "Make Herly feel like you.": "Herlyயை உங்களுக்கு ஏற்றதாக்குங்கள்.",
    "Color story": "வண்ணத் தொகுப்பு",
    "Herly Rose": "Herly ரோஜா",
    "Quiet Lavender": "அமைதியான லாவெண்டர்",
    "Soft Sage": "மென்மையான பச்சை",
    "Light & shade": "ஒளியும் நிழலும்",
    "Use device setting": "சாதன அமைப்பைப் பயன்படுத்து",
    "Dark": "இருள்",
    "A little preview": "ஒரு சிறு முன்னோட்டம்",
    "A calmer space. A clearer you.": "அமைதியான இடம். தெளிவான நீங்கள்.",
    "Your personal theme": "உங்கள் தனிப்பட்ட தோற்றம்",
    "Cancel": "ரத்து செய்",
    "Close": "மூடு",
    "Name": "பெயர்",
    "Your name": "உங்கள் பெயர்",
    "Email": "மின்னஞ்சல்",
    "Country": "நாடு",
    "Date of birth": "பிறந்த தேதி",
    "Understand my cycle": "என் சுழற்சியைப் புரிந்துகொள்",
    "Feel better day-to-day": "தினமும் நன்றாக உணருங்கள்",
    "Understand my body": "என் உடலைப் புரிந்துகொள்",
    "Self-care & beauty": "சுய பராமரிப்பும் அழகும்",
    "Manage stress": "மனஅழுத்தத்தைக் கையாளுங்கள்",
    "Sexual health": "பாலியல் ஆரோக்கியம்",
    "Trying for pregnancy": "கர்ப்பத்திற்கான முயற்சி",
    "Pregnancy": "கர்ப்பம்",
    "Motherhood": "தாய்மை",
    "What would you like Herly to help you with?":
        "Herly உங்களுக்கு எதில் உதவ வேண்டும்?",
    "Create your account": "உங்கள் கணக்கை உருவாக்குங்கள்",
    "A few details about you": "உங்களைப் பற்றிய சில விவரங்கள்",
    "Let’s understand your cycle": "உங்கள் சுழற்சியைப் புரிந்துகொள்வோம்",
    "Choose what matters to you. You can change this any time.": "உங்களுக்கு முக்கியமானதைத் தேர்ந்தெடுங்கள். எப்போது வேண்டுமானாலும் மாற்றலாம்.",
    "A little space for a healthier, happier you.":
        "ஆரோக்கியமான, மகிழ்ச்சியான உங்களுக்காக ஓர் இடம்.",
    "Make this space feel like yours.": "இந்த இடத்தை உங்களுடையதாக்குங்கள்.",
    "Your experience is unique. We’ll meet you where you are.":
        "உங்கள் அனுபவம் தனித்துவமானது. உங்களுடன் இருப்போம்.",
    "You control your data. Every permission is your choice.": "உங்கள் தரவு உங்கள் கட்டுப்பாட்டில். ஒவ்வோர் அனுமதியும் உங்கள் விருப்பம்.",
    "I get my period regularly": "எனக்கு மாதவிடாய் சீராக வருகிறது",
    "My cycle is sometimes irregular": "என் சுழற்சி சில நேரம் சீரற்றது",
    "I’m not sure yet": "எனக்கு இன்னும் உறுதியாகத் தெரியவில்லை",
    "I don’t get periods": "எனக்கு மாதவிடாய் வருவதில்லை",
    "Make yourself at home": "உங்கள் இடத்திற்கு வரவேற்கிறோம்",
    "Terms & Privacy": "விதிமுறைகளும் தனியுரிமையும்",
    "Biometric lock (demo)": "உயிரளவியல் பூட்டு (மாதிரி)",
    "Discreet notifications": "தனிப்பட்ட அறிவிப்புகள்",
    "Hide sensitive modules": "உணர்திறன் பகுதிகளை மறை",
    "AI personalization": "AI தனிப்பயனாக்கம்",
    "Enter a valid email address to continue.":
        "தொடர சரியான மின்னஞ்சலை உள்ளிடுங்கள்.",
    "Please add your name, date of birth, and country.":
        "பெயர், பிறந்த தேதி, நாடு ஆகியவற்றைச் சேருங்கள்.",
    "Welcome to your space. You’re all set.":
        "உங்கள் இடத்திற்கு வரவேற்கிறோம். அனைத்தும் தயார்.",
    "Estimates are for reflection only, never for contraception or diagnosis.":
        "மதிப்பீடுகள் சிந்தனைக்காக மட்டுமே; கருத்தடை அல்லது நோயறிதலுக்கு அல்ல.",
    "For You": "உங்களுக்காக",
    "Cycle": "சுழற்சி",
    "Mental wellbeing": "மன நல்வாழ்வு",
    "Lifestyle": "வாழ்க்கை முறை",
    "Relationships": "உறவுகள்",
    "A little understanding": "ஒரு சிறு புரிதல்",
    "Curiosity is a beautiful place to start.": "ஆர்வம் ஓர் அழகான தொடக்கம்.",
    "Find something for you": "உங்களுக்காக ஒன்றைத் தேடுங்கள்",
    "No articles found. Try another search.":
        "கட்டுரைகள் இல்லை. வேறு தேடலை முயலுங்கள்.",
    "Article not found": "கட்டுரை கிடைக்கவில்லை",
    "Return to the library to choose an article.":
        "கட்டுரையைத் தேர்ந்தெடுக்க நூலகத்திற்குத் திரும்புங்கள்.",
    "Finished reading": "வாசித்து முடித்தது",
    "Mark as read": "வாசித்ததாகக் குறி",
    "Getting to know your cycle": "உங்கள் சுழற்சியை அறிதல்",
    "A softer landing at bedtime": "தூக்கத்திற்கு மென்மையான தொடக்கம்",
    "Make room for yourself": "உங்களுக்காக இடம் ஒதுக்குங்கள்",
    "Food, culture, and everyday care":
        "உணவு, பண்பாடு மற்றும் தினசரி பராமரிப்பு",
    "Consent and boundaries": "சம்மதமும் எல்லைகளும்",
    "A gentle reminder": "மென்மையான நினைவூட்டல்",
    "Edit reminder": "நினைவூட்டலைத் திருத்து",
    "Daily": "தினமும்",
    "Weekdays": "வார நாட்கள்",
    "Weekly": "வாரந்தோறும்",
    "Edit": "திருத்து",
    "Delete reminder": "நினைவூட்டலை நீக்கு",
    "Add a reminder": "நினைவூட்டலைச் சேர்",
    "A moment for water": "தண்ணீருக்காக ஒரு கணம்",
    "Evening wind-down": "மாலை ஓய்வு",
    "Vitamins": "வைட்டமின்கள்",
    "Please complete your profile with a valid email.":
        "சரியான மின்னஞ்சலுடன் சுயவிவரத்தை நிறைவு செய்யுங்கள்.",
    "Profile updated.": "சுயவிவரம் புதுப்பிக்கப்பட்டது.",
    "A fresh page is waiting for you.":
        "ஒரு புதிய பக்கம் உங்களுக்காகக் காத்திருக்கிறது.",
    "A mindful minute": "கவனமான ஒரு நிமிடம்",
    "A moment for you": "உங்களுக்காக ஒரு கணம்",
    "A moment outdoors": "வெளியில் ஒரு கணம்",
    "A quiet place. Just for you.": "அமைதியான இடம். உங்களுக்காக மட்டும்.",
    "A safer, happier\nyou": "பாதுகாப்பான,\nமகிழ்ச்சியான நீங்கள்",
    "About Herly": "Herly பற்றி",
    "About this preview": "இந்த முன்னோட்டம் பற்றி",
    "Add a product note": "தயாரிப்புக் குறிப்பைச் சேர்",
    "Add a sample contact to explore this workflow.":
        "இச்செயல்முறையைப் பார்க்க மாதிரித் தொடர்பைச் சேருங்கள்.",
    "Add trusted contact": "நம்பகமான தொடர்பைச் சேர்",
    "Advanced personal insights": "மேம்பட்ட தனிப்பட்ட நுண்ணறிவு",
    "Begin a quiet moment": "அமைதியான கணத்தைத் தொடங்கு",
    "Body": "உடல்",
    "Care that fits your day.": "உங்கள் நாளுக்கேற்ற பராமரிப்பு.",
    "Choose a section from More.":
        "மேலும் என்பதிலிருந்து ஒரு பகுதியைத் தேர்ந்தெடுங்கள்.",
    "Close preview": "முன்னோட்டத்தை மூடு",
    "Configured cycle": "அமைத்த சுழற்சி",
    "Configured period": "அமைத்த மாதவிடாய் காலம்",
    "Contextual Herly AI": "சூழல்சார் Herly AI",
    "Copy JSON": "JSON நகலெடு",
    "Could not load a response. Please try again.":
        "பதிலை ஏற்ற முடியவில்லை. மீண்டும் முயலவும்.",
    "Cycle tracking is off": "சுழற்சிக் கண்காணிப்பு முடக்கப்பட்டுள்ளது",
    "Delete data": "தரவை நீக்கு",
    "Delete local demo data": "உள்ளூர் மாதிரித் தரவை நீக்கு",
    "Delete your local data?": "உங்கள் உள்ளூர்த் தரவை நீக்கவா?",
    "Demo membership active": "மாதிரி உறுப்பினர் நிலை செயலில்",
    "Demo preview · About these insights":
        "மாதிரி முன்னோட்டம் · இந்நுண்ணறிவு பற்றி",
    "Demo pricing only. No payment, subscription, or automatic renewal occurs. Premium capabilities are concept previews.": "மாதிரி விலை மட்டுமே. கட்டணம், சந்தா அல்லது தானியங்கு புதுப்பிப்பு இல்லை. சிறப்பு வசதிகள் கருத்து முன்னோட்டங்கள்.",
    "Demo sign-in · No connection to Google or Apple is made.":
        "மாதிரி உள்நுழைவு · Google அல்லது Apple உடன் இணைப்பு இல்லை.",
    "Demo terms & privacy": "மாதிரி விதிகளும் தனியுரிமையும்",
    "Demo: location sharing would expire in 15 minutes. No location is accessed or shared.": "மாதிரி: இருப்பிடப் பகிர்வு 15 நிமிடங்களில் முடியும். இருப்பிடம் அணுகப்படவோ பகிரப்படவோ இல்லை.",
    "Earlier": "முன்பு",
    "Recent": "சமீபத்தில்",
    "End demo membership": "மாதிரி உறுப்பினர் நிலையை முடி",
    "Enhanced personalization": "மேம்பட்ட தனிப்பயனாக்கம்",
    "Enter a valid email address.": "சரியான மின்னஞ்சலை உள்ளிடுங்கள்.",
    "Evening skincare": "மாலைச் சருமப் பராமரிப்பு",
    "Every rhythm\nis personal.": "ஒவ்வொரு தாளமும்\nதனிப்பட்டது.",
    "Explain my recent pattern": "என் சமீபத்திய முறையை விளக்குங்கள்",
    "Explore Herly+ demo": "Herly+ மாதிரியை ஆராயுங்கள்",
    "Export copied to clipboard.": "ஏற்றுமதி நகலெடுக்கப்பட்டது.",
    "Export my data": "என் தரவை ஏற்றுமதி செய்",
    "Feel better\nevery day": "தினமும்\nநன்றாக உணருங்கள்",
    "Finding support": "உதவி பெறுதல்",
    "Got it": "புரிந்தது",
    "HERLY EDITORIAL · DEMO CONTENT · 3 MIN":
        "HERLY கட்டுரை · மாதிரி உள்ளடக்கம் · 3 நிமிடம்",
    "HERLY · HER LIFE. HER WAY.\nLocal demo · version 1.0":
        "HERLY · அவள் வாழ்க்கை. அவள் வழி.\nஉள்ளூர் மாதிரி · பதிப்பு 1.0",
    "Hair care": "முடிப் பராமரிப்பு",
    "Herly is a local prototype. Entries are stored on this device using unencrypted app preferences. Use sample information only. No account is created and no medical service is provided.": "Herly ஓர் உள்ளூர் முன்மாதிரி. பதிவுகள் இச்சாதனத்தில் குறியாக்கமில்லா அமைப்புகளில் சேமிக்கப்படும். மாதிரித் தகவலை மட்டும் பயன்படுத்துங்கள். கணக்கு உருவாக்கமோ மருத்துவச் சேவையோ இல்லை.",
    "Herly+ demo activated. No charge was made.":
        "Herly+ மாதிரி இயக்கப்பட்டது. கட்டணம் இல்லை.",
    "Herly · Her Life. Her Way.": "Herly · அவள் வாழ்க்கை. அவள் வழி.",
    "Herly. Her Life. Her Way.": "Herly. அவள் வாழ்க்கை. அவள் வழி.",
    "Herly. Her Life. Her Way. Loading your welcome screen.":
        "Herly. அவள் வாழ்க்கை. அவள் வழி. வரவேற்புத் திரை ஏற்றப்படுகிறது.",
    "Hi, I’m Herly. A little space to ask, reflect, and feel heard. How can I help today?": "வணக்கம், நான் Herly. கேட்கவும் சிந்திக்கவும் ஓர் இடம். இன்று எப்படி உதவலாம்?",
    "ILLUSTRATIVE DEMO CHART": "விளக்க மாதிரி வரைபடம்",
    "If you are in immediate danger, contact your local emergency services. This prototype does not make calls, send messages, or share location.": "உடனடி ஆபத்தில் இருந்தால் உள்ளூர் அவசரச் சேவைகளை அணுகுங்கள். இம்முன்மாதிரி அழைப்புகள், செய்திகள் அல்லது இருப்பிடப் பகிர்வு செய்யாது.",
    "Keep data": "தரவை வைத்திரு",
    "Latest entry": "சமீபத்திய பதிவு",
    "Log a few check-ins to see your own observations.":
        "உங்கள் கவனிப்புகளைக் காண சில பதிவுகளைச் சேருங்கள்.",
    "Log a skin observation": "சருமக் கவனிப்பைப் பதிவு செய்",
    "Longer history & reports": "நீண்ட வரலாறும் அறிக்கைகளும்",
    "More room for your story.": "உங்கள் கதைக்கு அதிக இடம்.",
    "Morning skincare": "காலைச் சருமப் பராமரிப்பு",
    "Name and phone": "பெயரும் தொலைபேசியும்",
    "Nothing logged yet. Start with how you feel.":
        "இன்னும் பதிவுகள் இல்லை. உங்கள் உணர்வுடன் தொடங்குங்கள்.",
    "Notice. Reflect.\nUnderstand.":
        "கவனியுங்கள். சிந்தியுங்கள்.\nபுரிந்துகொள்ளுங்கள்.",
    "Nov 15": "நவ 15",
    "Nov 2 – 6": "நவ 2 – 6",
    "Nov 2 – Nov 6": "நவ 2 – நவ 6",
    "Nov 24": "நவ 24",
    "Nov 4": "நவ 4",
    "Nov 4 (est.)": "நவ 4 (மதிப்பீடு)",
    "Oct 27": "அக் 27",
    "Oct 31": "அக் 31",
    "Nutrition and energy": "ஊட்டச்சத்தும் ஆற்றலும்",
    "Open selected calendar date": "தேர்ந்தெடுத்த தேதியைத் திற",
    "PIN preview": "PIN முன்னோட்டம்",
    "PIN preview complete. No lock is enabled.":
        "PIN முன்னோட்டம் முடிந்தது. பூட்டு இயக்கப்படவில்லை.",
    "Patterns to reflect on. A story only you can tell.":
        "சிந்திக்க சில முறைகள். நீங்கள் மட்டுமே சொல்லக்கூடிய கதை.",
    "Pause. Notice your surroundings. Give yourself a little room to breathe.": "நிறுத்துங்கள். சுற்றுப்புறத்தைக் கவனியுங்கள். சுவாசிக்கச் சிறிது இடம் கொடுங்கள்.",
    "Personalized responses are turned off. You can choose whether to enable them in Privacy & Security.": "தனிப்பயன் பதில்கள் முடக்கப்பட்டுள்ளன. தனியுரிமை மற்றும் பாதுகாப்பில் இயக்கலாம்.",
    "Photo storage is a demo placeholder.": "படச் சேமிப்பு ஒரு மாதிரி வசதி.",
    "Photo upload preview": "படப் பதிவேற்ற முன்னோட்டம்",
    "Premium routines": "சிறப்பு வழக்கங்கள்",
    "Preview": "முன்னோட்டம்",
    "Preview a safety check-in": "பாதுகாப்புப் பதிவு முன்னோட்டம்",
    "Preview temporary location sharing":
        "தற்காலிக இருப்பிடப் பகிர்வு முன்னோட்டம்",
    "Progress photos": "முன்னேற்றப் படங்கள்",
    "Prototype privacy: data stays in this browser or device, in unencrypted local storage. Biometrics and notifications are interface demos.": "முன்மாதிரித் தனியுரிமை: தரவு இந்த உலாவி அல்லது சாதனத்தில் குறியாக்கமில்லாமல் இருக்கும். உயிரளவியலும் அறிவிப்புகளும் இடைமுக மாதிரிகள்.",
    "Quick check-in": "விரைவுப் பதிவு",
    "Reach out to a trusted person, a qualified healthcare professional, or a local support organization. For urgent assistance, use the emergency services available in your location.": "நம்பகமானவர், தகுதியான சுகாதார நிபுணர் அல்லது உள்ளூர் உதவி அமைப்பை அணுகுங்கள். அவசர உதவிக்கு உங்கள் பகுதியின் அவசரச் சேவைகளைப் பயன்படுத்துங்கள்.",
    "Reflection": "சிந்தனைப் பதிவு",
    "Remove contact": "தொடர்பை அகற்று",
    "Safety check-in preview": "பாதுகாப்புப் பதிவு முன்னோட்டம்",
    "Save a reflection": "சிந்தனைப் பதிவைச் சேமி",
    "Set demo PIN": "மாதிரி PIN அமை",
    "Small nudges, on your terms. Scheduling is a demo; no notifications are sent.": "உங்கள் விருப்பப்படி நினைவூட்டல்கள். அட்டவணை ஒரு மாதிரி; அறிவிப்புகள் அனுப்பப்படாது.",
    "Small steps. A little more balance.":
        "சிறிய அடிகள். இன்னும் சிறிது சமநிலை.",
    "Sri Lanka": "இலங்கை",
    "Take this moment at your own pace.":
        "இக்கணத்தை உங்கள் வேகத்தில் அனுபவியுங்கள்.",
    "There is no one right journey.": "அனைவருக்கும் ஒரே சரியான பயணம் இல்லை.",
    "This care directory is a design preview. No provider search, location access, or booking takes place.": "இப்பராமரிப்புப் பட்டியல் வடிவமைப்பு முன்னோட்டம். சேவை தேடல், இருப்பிட அணுகல் அல்லது முன்பதிவு இல்லை.",
    "This chart uses sample values to demonstrate the design. Your saved entries appear below. No medical correlations or diagnoses are inferred.": "இவ்வரைபடம் மாதிரி மதிப்புகளைப் பயன்படுத்துகிறது. உங்கள் பதிவுகள் கீழே உள்ளன. மருத்துவத் தொடர்புகளோ நோயறிதலோ ஊகிக்கப்படவில்லை.",
    "This removes your profile, logs, chats, and preferences from this demo. This cannot be undone.": "இது சுயவிவரம், பதிவுகள், உரையாடல்கள் மற்றும் அமைப்புகளை நீக்கும். இதை மீட்க முடியாது.",
    "Tips for better sleep": "சிறந்த தூக்கத்திற்கான ஆலோசனைகள்",
    "Today, I’m grateful for…": "இன்று நான் நன்றியுடன் இருப்பது…",
    "Trusted contact (demo)": "நம்பகமான தொடர்பு (மாதிரி)",
    "Trusted people": "நம்பகமானவர்கள்",
    "Tue, 28 Oct 2026": "28 அக்டோபர் 2026",
    "Understand\nyour body": "உங்கள் உடலைப்\nபுரிந்துகொள்ளுங்கள்",
    "Understand yourself\nmore deeply.":
        "உங்களை மேலும்\nஆழமாகப் புரிந்துகொள்ளுங்கள்.",
    "Version 1.0.0 · Made with care":
        "பதிப்பு 1.0.0 · அக்கறையுடன் உருவாக்கியது",
    "Voice note · demo": "குரல் பதிவு · மாதிரி",
    "Voice recording is a demo placeholder.": "குரல் பதிவு ஒரு மாதிரி வசதி.",
    "What’s on your mind?": "உங்கள் மனதில் என்ன இருக்கிறது?",
    "Write a little something first.": "முதலில் சிறிது எழுதுங்கள்.",
    "You decide what to share. Always.":
        "பகிர்வதை நீங்களே முடிவு செய்கிறீர்கள். எப்போதும்.",
    "You deserve to feel safe and supported.":
        "பாதுகாப்பும் ஆதரவும் பெற நீங்கள் தகுதியானவர்.",
    "Your daily ritual": "உங்கள் தினசரி வழக்கம்",
    "Your data export": "உங்கள் தரவு ஏற்றுமதி",
    "Your energy may be slightly lower today.\nTry some light exercise and stay hydrated.": "இன்று ஆற்றல் சற்று குறையலாம்.\nலேசாக உடற்பயிற்சி செய்து தண்ணீர் அருந்துங்கள்.",
    "Your entries": "உங்கள் பதிவுகள்",
    "Your observations": "உங்கள் கவனிப்புகள்",
    "Your observations, together in one place.":
        "உங்கள் கவனிப்புகள் ஒரே இடத்தில்.",
    "Your patterns start here": "உங்கள் முறைகள் இங்கு தொடங்குகின்றன",
    "Your reflection is saved.": "உங்கள் சிந்தனைப் பதிவு சேமிக்கப்பட்டது.",
    "Your reflections": "உங்கள் சிந்தனைப் பதிவுகள்",
    "Your story starts with a check-in. A few moments today can help you notice your own patterns.": "உங்கள் கதை ஒரு பதிவில் தொடங்குகிறது. இன்றைய சில கணங்கள் உங்கள் முறைகளைக் கவனிக்க உதவும்.",
    "4 digits · not stored": "4 இலக்கங்கள் · சேமிக்கப்படாது",
    "glasses (0–30)": "குவளைகள் (0–30)",
    "hours (0–24)": "மணிநேரம் (0–24)",
    "kg (1–500)": "கிலோ (1–500)",
    "minutes (0–1440)": "நிமிடங்கள் (0–1440)",
    "steps (0–100000)": "நடைகள் (0–100000)",
    "Annual · LKR 4,900 / year": "ஆண்டு · வருடத்திற்கு ரூ. 4,900",
    "Monthly · LKR 590 / month": "மாதம் · மாதத்திற்கு ரூ. 590",
    "3 min read · Demo content →": "3 நிமிட வாசிப்பு · மாதிரி உள்ளடக்கம் →",
    "A gentle evening routine can be a useful place to start. Try a consistent wind-down time, a comfortable room, and a few quiet minutes away from screens. What helps you feel settled?": "மென்மையான மாலை வழக்கம் நல்ல தொடக்கமாக இருக்கலாம். சீரான ஓய்வு நேரம், வசதியான அறை, திரைகளிலிருந்து விலகிய அமைதியான சில நிமிடங்களை முயலுங்கள். எது உங்களுக்கு அமைதி தருகிறது?",
    "I can help you record when discomfort happens and prepare questions for a clinician. This is a simulated conversation, not a diagnosis. Severe, unusual, or worsening pain deserves professional attention.": "அசௌகரியம் ஏற்படும் நேரத்தைப் பதியவும் மருத்துவருக்கான கேள்விகளைத் தயாரிக்கவும் உதவ முடியும். இது மாதிரி உரையாடல்; நோயறிதல் அல்ல. கடுமையான, வழக்கமற்ற அல்லது அதிகரிக்கும் வலிக்கு நிபுணரை அணுகுங்கள்.",
    "That sounds difficult. You could take a quiet moment and notice what is around you, or reach out to someone you trust. Would you like to write down how you feel?": "அது கடினமாகத் தெரிகிறது. அமைதியாகச் சுற்றுப்புறத்தைக் கவனிக்கலாம் அல்லது நம்பகமான ஒருவரை அணுகலாம். உங்கள் உணர்வுகளை எழுத விரும்புகிறீர்களா?",
    "Your demo history includes several mood and sleep entries. These are examples, not a medical finding. Keep logging what you notice to build a more useful personal record.": "மாதிரி வரலாற்றில் மனநிலை மற்றும் தூக்கப் பதிவுகள் உள்ளன. இவை எடுத்துக்காட்டுகள்; மருத்துவக் கண்டுபிடிப்புகள் அல்ல. பயனுள்ள தனிப்பட்ட பதிவிற்குத் தொடர்ந்து பதியுங்கள்.",
    "Thank you for sharing. I’m a demo wellbeing companion with scripted replies. You can use your journal to reflect, log how you feel, or explore the learning library. What would feel useful today?": "பகிர்ந்ததற்கு நன்றி. நான் முன்கூட்டியே எழுதப்பட்ட பதில்களைக் கொண்ட மாதிரி நல்வாழ்வுத் துணை. நாட்குறிப்பில் சிந்திக்கலாம், உணர்வுகளைப் பதியலாம் அல்லது நூலகத்தை ஆராயலாம். இன்று எது பயனுள்ளதாக இருக்கும்?",
    "SAFETY: This demo cannot assess urgent symptoms or provide crisis care. If you may be in immediate danger, contact local emergency services or a trusted person now. Seek professional help promptly for severe or worsening symptoms.": "பாதுகாப்பு: இம்மாதிரியால் அவசர அறிகுறிகளை மதிப்பிடவோ நெருக்கடி பராமரிப்பு வழங்கவோ முடியாது. உடனடி ஆபத்து இருந்தால் உள்ளூர் அவசரச் சேவைகள் அல்லது நம்பகமானவரை இப்போது அணுகுங்கள். கடுமையான அல்லது அதிகரிக்கும் அறிகுறிகளுக்கு விரைவாக நிபுணர் உதவி பெறுங்கள்.",
    "I’m sorry to hear you’re feeling more tired 💜":
        "நீங்கள் அதிகச் சோர்வுடன் இருப்பது வருத்தமளிக்கிறது 💜",
    "Energy can change for many reasons. Recording how you feel alongside your cycle can help you notice patterns. This sample conversation cannot determine the cause.": "பல காரணங்களால் ஆற்றல் மாறலாம். சுழற்சியுடன் உணர்வுகளைப் பதிவது முறைகளைக் கவனிக்க உதவும். இந்த மாதிரி உரையாடலால் காரணத்தைத் தீர்மானிக்க முடியாது.",
    "Here are a few gentle things that may help:":
        "உதவக்கூடிய சில மென்மையான வழிகள்:",
    "💧  Stay hydrated": "💧  போதிய தண்ணீர் அருந்துங்கள்",
    "🌿  Try light movement like a short walk":
        "🌿  குறுகிய நடை போன்ற மென்மையான இயக்கத்தை முயலுங்கள்",
    "🌙  Get a little extra rest": "🌙  சிறிது கூடுதல் ஓய்வெடுங்கள்",
    "💗  Include iron-rich foods in your meals":
        "💗  உணவில் இரும்புச்சத்து உணவுகளைச் சேருங்கள்",
    "Everyone’s experience is different. If your fatigue feels severe or continues, speak with a doctor.": "ஒவ்வொருவரின் அனுபவமும் வேறுபடும். சோர்வு கடுமையாக இருந்தாலோ தொடர்ந்தாலோ மருத்துவரிடம் பேசுங்கள்.",
    "Your cycle is a personal pattern, and it can change. Recording dates and observations can help you describe your experience.": "உங்கள் சுழற்சி தனிப்பட்ட முறை; அது மாறலாம். தேதிகளையும் கவனிப்புகளையும் பதிவது அனுபவத்தை விவரிக்க உதவும்.",
    "Try noting the first day of bleeding, how you feel, and anything you want to discuss with a clinician. Estimates in Herly are illustrative and are not suitable for contraception.": "இரத்தப்போக்கின் முதல் நாள், உணர்வுகள் மற்றும் மருத்துவரிடம் பேச வேண்டியவற்றைப் பதியுங்கள். Herly மதிப்பீடுகள் விளக்கத்திற்கானவை; கருத்தடைக்கு ஏற்றவை அல்ல.",
    "Reflection: what would you like to understand about your own pattern?":
        "சிந்தனை: உங்கள் முறையைப் பற்றி எதைப் புரிந்துகொள்ள விரும்புகிறீர்கள்?",
    "An evening ritual can be as simple as a few quiet minutes. Choose something that feels comfortable and repeatable.": "மாலை வழக்கம் அமைதியான சில நிமிடங்களாக இருக்கலாம். வசதியாகவும் மீண்டும் செய்யக்கூடியதாகவும் ஒன்றைத் தேர்ந்தெடுங்கள்.",
    "Write down tomorrow’s priorities, put your phone aside, and make space to rest. This is illustrative wellness content, not clinical advice.": "நாளைய முன்னுரிமைகளை எழுதுங்கள், தொலைபேசியை ஒதுக்கி ஓய்வெடுங்கள். இது விளக்க நல்வாழ்வு உள்ளடக்கம்; மருத்துவ ஆலோசனை அல்ல.",
    "Self-care does not need a perfect routine. Pick one small action that feels kind today.": "சுய பராமரிப்பிற்கு முழுமையான வழக்கம் தேவையில்லை. இன்று அன்பான ஒரு சிறு செயலைத் தேர்ந்தெடுங்கள்.",
    "A short walk, a favourite song, or a moment with your journal can be your starting point.": "குறுகிய நடை, பிடித்த பாடல் அல்லது நாட்குறிப்புடன் ஒரு கணம் தொடக்கமாக இருக்கலாம்.",
    "Use this demo journal to notice meals you enjoy and questions you have about nutrition.": "விரும்பிய உணவுகளையும் ஊட்டச்சத்துக் கேள்விகளையும் கவனிக்க இம்மாதிரி நாட்குறிப்பைப் பயன்படுத்துங்கள்.",
    "For personalized dietary guidance, speak with a qualified professional. Herly’s learning library is sample content.": "தனிப்பட்ட உணவு வழிகாட்டலுக்குத் தகுதியான நிபுணரிடம் பேசுங்கள். Herly நூலகம் மாதிரி உள்ளடக்கம் கொண்டது.",
    "Your boundaries matter. You can change your mind, ask for time, and choose what feels comfortable.": "உங்கள் எல்லைகள் முக்கியம். மனதை மாற்றலாம், நேரம் கேட்கலாம், வசதியானதைத் தேர்ந்தெடுக்கலாம்.",
    "Healthy conversations leave room for mutual respect and a clear, freely given choice.": "நலமான உரையாடல்கள் பரஸ்பர மரியாதைக்கும் தெளிவான சுதந்திரத் தேர்வுக்கும் இடமளிக்கும்.",
    "Your privacy, made clear": "உங்கள் தனியுரிமை தெளிவாக",
    "This prototype stores sample data on this device in unencrypted app preferences. No backend or live AI receives your entries. Biometrics and PIN are demonstrations, not security protections.": "இம்முன்மாதிரி மாதிரித் தரவைச் சாதனத்தில் குறியாக்கமில்லாமல் சேமிக்கும். சேவையகமோ நேரடி AIயோ பதிவுகளைப் பெறாது. உயிரளவியலும் PINனும் விளக்கங்கள்; பாதுகாப்பு முறைகள் அல்ல.",
    "“I’d appreciate a check-in. Could you contact me?”": "“என் நிலையை விசாரித்தால் நன்றாக இருக்கும். என்னைத் தொடர்புகொள்ள முடியுமா?”",
    "Demo only. Nothing is sent.": "மாதிரி மட்டும். எதுவும் அனுப்பப்படாது.",
    "Unlogged metrics, fertility dates, and the daily insight are sample content from the design reference. They are not personalized medical predictions. Saved check-ins replace the corresponding sample metric. Do not use cycle estimates for contraception. Doctor services are visual previews.": "பதியாத அளவுகள், கருவுறும் தேதிகள் மற்றும் தினசரி நுண்ணறிவு வடிவமைப்பின் மாதிரி உள்ளடக்கம். இவை தனிப்பட்ட மருத்துவக் கணிப்புகள் அல்ல. சேமித்த பதிவுகள் மாதிரி அளவை மாற்றும். சுழற்சி மதிப்பீடுகளை கருத்தடைக்குப் பயன்படுத்தாதீர்கள். மருத்துவச் சேவைகள் காட்சி முன்னோட்டங்கள்.",
    "Herly is a runnable Flutter design prototype for a personal wellbeing companion.": "Herly ஒரு தனிப்பட்ட நல்வாழ்வுத் துணைக்கான இயங்கும் Flutter வடிவமைப்பு முன்மாதிரி.",
    "Tracking, preferences, reminders, and chat history are saved locally. Authentication, AI, subscriptions, security locks, notifications, and safety actions are simulations.": "பதிவுகள், அமைப்புகள், நினைவூட்டல்கள் மற்றும் உரையாடல்கள் உள்ளூரில் சேமிக்கப்படும். உள்நுழைவு, AI, சந்தா, பூட்டுகள், அறிவிப்புகள் மற்றும் பாதுகாப்புச் செயல்கள் மாதிரிகள்.",
    "English, Sinhala and Tamil interface text changes with your language setting. Your own notes and messages stay as you wrote them.": "மொழி அமைப்பின்படி ஆங்கிலம், சிங்களம் மற்றும் தமிழ் இடைமுக உரை மாறும். உங்கள் குறிப்புகளும் செய்திகளும் எழுதியபடியே இருக்கும்.",
    "Use sample data only. This prototype does not provide diagnosis or emergency services.": "மாதிரித் தரவை மட்டும் பயன்படுத்துங்கள். இம்முன்மாதிரி நோயறிதல் அல்லது அவசரச் சேவை வழங்காது.",
    "Track Your Cycle": "உங்கள் சுழற்சியைக் கண்காணிக்கவும்",
    "Plan Your Goals": "உங்கள் இலக்குகளைத் திட்டமிடுங்கள்",
    "Set Reminders": "நினைவூட்டல்களை அமையுங்கள்",
    "Ask Herly AI": "Herly AIயிடம் கேளுங்கள்",
    "Online Consultation": "இணைய ஆலோசனை",
    "Nearby Clinics": "அருகிலுள்ள மருத்துவமனைகள்",
    "Emergency Support": "அவசர உதவி",
  },
};
const templates = {
  'si': {
    'You have recorded {n} mood check-ins. These observations describe your logs; they do not establish a medical cause.': 'ඔබ මනෝභාව සටහන් {n} ක් ලියා ඇත. මේවා ඔබේ සටහන් විස්තර කරන අතර වෛද්‍ය හේතුවක් තහවුරු නොකරයි.',
    'You have recorded {n} mood check-in. These observations describe your logs; they do not establish a medical cause.':
        'ඔබ මනෝභාව සටහන් {n} ක් ලියා ඇත. මේවා වෛද්‍ය හේතුවක් තහවුරු නොකරයි.',
    '{n} days': 'දින {n}',
    'Day {n}': 'දින {n}',
    'of {n}': '{n} න්',
    'In {n} days': 'දින {n} කින්',
    'Period Day {n}': 'ඔසප් දින {n}',
    '{n} min read': 'කියවීමට විනාඩි {n}',
    'Log {kind}': '{kind} සටහන් කරන්න',
    'Continue with {method}': '{method} සමඟ ඉදිරියට',
    'YOUR JOURNEY  /  {n}': 'ඔබේ ගමන / {n}',
    'Average cycle · {n} days': 'සාමාන්‍ය චක්‍රය · දින {n}',
    'Average period · {n} days': 'සාමාන්‍ය ඔසප් කාලය · දින {n}',
    'Last period · {date}': 'අවසන් ඔසප් වීම · {date}',
    '{n} of 4 done': '4 න් {n} ක් අවසන්',
    'Drink {n}/8 cups': 'වතුර කෝප්ප {n}/8 බොන්න',
    'Step goal {n}': 'පියවර ඉලක්කය {n}',
    'Sleep {n}': 'නින්ද {n}',
    '{n}/8 cups': 'කෝප්ප {n}/8',
    '{n}h {m}m': 'පැය {n} විනාඩි {m}',
    'Cycle day {n} · based on your dates': 'චක්‍රයේ දින {n} · ඔබේ දින අනුව',
    'YOUR {kind} STORY': 'ඔබේ {kind} කතාව',
    '{kind} over time': 'කාලය සමඟ {kind}',
    '{n} glasses today': 'අද වතුර වීදුරු {n}',
    '{n} minutes today': 'අද විනාඩි {n}',
    '{n} hours today': 'අද පැය {n}',
    'Enter a valid number of {unit}.': 'වලංගු {unit} ගණනක් ඇතුළත් කරන්න.',
    '{kind} saved. A little more in tune with you.':
        '{kind} සුරැකිණි. ඔබ ගැන තවත් අවබෝධයක්.',
    'Cycle day {n} of {length}': 'චක්‍ර දින {n}, {length} න්',
  },
  'ta': {
    'You have recorded {n} mood check-ins. These observations describe your logs; they do not establish a medical cause.': 'நீங்கள் {n} மனநிலைப் பதிவுகளைச் செய்துள்ளீர்கள். இவை உங்கள் பதிவுகளை விவரிக்கும்; மருத்துவக் காரணத்தை நிறுவாது.',
    'You have recorded {n} mood check-in. These observations describe your logs; they do not establish a medical cause.': 'நீங்கள் {n} மனநிலைப் பதிவைச் செய்துள்ளீர்கள். இது மருத்துவக் காரணத்தை நிறுவாது.',
    '{n} days': '{n} நாட்கள்',
    'Day {n}': 'நாள் {n}',
    'of {n}': '{n} இல்',
    'In {n} days': '{n} நாட்களில்',
    'Period Day {n}': 'மாதவிடாய் நாள் {n}',
    '{n} min read': '{n} நிமிட வாசிப்பு',
    'Log {kind}': '{kind} பதிவு செய்',
    'Continue with {method}': '{method} மூலம் தொடரவும்',
    'YOUR JOURNEY  /  {n}': 'உங்கள் பயணம் / {n}',
    'Average cycle · {n} days': 'சராசரி சுழற்சி · {n} நாட்கள்',
    'Average period · {n} days': 'சராசரி மாதவிடாய் · {n} நாட்கள்',
    'Last period · {date}': 'கடைசி மாதவிடாய் · {date}',
    '{n} of 4 done': '4 இல் {n} முடிந்தது',
    'Drink {n}/8 cups': '{n}/8 கிண்ணம் தண்ணீர்',
    'Step goal {n}': 'நடை இலக்கு {n}',
    'Sleep {n}': 'தூக்கம் {n}',
    '{n}/8 cups': '{n}/8 கிண்ணங்கள்',
    '{n}h {m}m': '{n} மணி {m} நிமிடம்',
    'Cycle day {n} · based on your dates':
        'சுழற்சி நாள் {n} · உங்கள் தேதிகளின் அடிப்படையில்',
    'YOUR {kind} STORY': 'உங்கள் {kind} கதை',
    '{kind} over time': 'காலப்போக்கில் {kind}',
    '{n} glasses today': 'இன்று {n} குவளைகள்',
    '{n} minutes today': 'இன்று {n} நிமிடங்கள்',
    '{n} hours today': 'இன்று {n} மணிநேரம்',
    'Enter a valid number of {unit}.': 'சரியான {unit} எண்ணை உள்ளிடுங்கள்.',
    '{kind} saved. A little more in tune with you.':
        '{kind} சேமிக்கப்பட்டது. உங்களை மேலும் புரிந்துகொள்ளுங்கள்.',
    'Cycle day {n} of {length}': 'சுழற்சி நாள் {n}, மொத்தம் {length}',
  },
};
